# Setup


In [2]:
%load_ext sql

In [3]:
import prettytable
import sqlalchemy

prettytable.__dict__['DEFAULT'] = prettytable.DEFAULT

%config SqlMagic.style ='default'

/tmp/ipykernel_25356/102533596.py:4: DeprecationWarning: the 'DEFAULT' constant is deprecated, use the 'TableStyle' enum instead
  prettytable.__dict__['DEFAULT'] = prettytable.DEFAULT


In [4]:
%sql postgresql://postgres:postgresman30@localhost:5432/db_a1

## Basic Queries

1. List the subject_id of all female patients with anchor age more than 89.
    
    output columns: subject_id
    
    order by columns: subject_id

In [17]:
%%sql select subject_id from hosp.patients
where anchor_age > 89 and gender = 'F'
order by subject_id;

 * postgresql://postgres:***@localhost:5432/db_a1
2 rows affected.


[(10012853,), (10020640,)]

In [5]:
%%sql
SELECT subject_id FROM hosp.patients 
where anchor_age>89 and gender='F' 
order by subject_id;

 * postgresql://postgres:***@localhost:5432/db_a1
2 rows affected.


[(10012853,), (10020640,)]

2. List the top 5 years in which the most number of patients were admitted to hospitals.
    
    output columns: count, year
    
    order by columns: count(descending), year

In [85]:
%%sql
SELECT COUNT(DISTINCT SUBJECT_ID) AS count,
EXTRACT(YEAR FROM TO_TIMESTAMP(admittime, 'YYYY-MM-DD HH24:MI:SS')) AS year 
FROM hosp.admissions
GROUP BY year
ORDER BY count DESC, year
LIMIT 5;

 * postgresql://postgres:***@localhost:5432/db_a1
5 rows affected.


[(7, Decimal('2137')),
 (7, Decimal('2148')),
 (4, Decimal('2113')),
 (4, Decimal('2115')),
 (4, Decimal('2129'))]

In [4]:
%%sql
select count(distinct subject_id), DATE_PART('year', TO_TIMESTAMP(admittime, 'YYYY-MM-DD HH24:MI:SS'))::INTEGER as year  
from hosp.admissions 
group by DATE_PART('year', TO_TIMESTAMP(admittime, 'YYYY-MM-DD HH24:MI:SS')) 
order by count(distinct subject_id) desc, year limit 5;

 * postgresql://postgres:***@localhost:5432/db_a1
5 rows affected.


[(7, 2137), (7, 2148), (4, 2113), (4, 2115), (4, 2129)]

3. List the hadm_id, gender, admission duration(**HH:MM:SS or** X days, HH:MM:SS) of all admissions which have non-null dischtime. Admission duration is defined as the difference between dischtime and admittime.
    
    output columns: hadm_id, gender, duration
    
    order by columns: duration, hadm_id

In [27]:
%%sql
SELECT a.hadm_id, 
       p.gender, 
       JUSTIFY_INTERVAL(TO_TIMESTAMP(a.dischtime, 'YYYY-MM-DD HH24:MI:SS') - 
                        TO_TIMESTAMP(a.admittime, 'YYYY-MM-DD HH24:MI:SS')) AS duration
FROM hosp.admissions a
JOIN hosp.patients p ON a.subject_id = p.subject_id
WHERE a.dischtime IS NOT NULL
ORDER BY duration, a.hadm_id;


 * postgresql://postgres:***@localhost:5432/db_a1
275 rows affected.


[(22999601, 'F', datetime.timedelta(seconds=4020)),
 (22896692, 'F', datetime.timedelta(seconds=8280)),
 (23199774, 'M', datetime.timedelta(seconds=10800)),
 (21390688, 'F', datetime.timedelta(seconds=13500)),
 (28697806, 'F', datetime.timedelta(seconds=16980)),
 (22380825, 'F', datetime.timedelta(seconds=19560)),
 (25282382, 'F', datetime.timedelta(seconds=28020)),
 (26332470, 'F', datetime.timedelta(seconds=35640)),
 (23143086, 'M', datetime.timedelta(seconds=40380)),
 (28543425, 'F', datetime.timedelta(seconds=40620)),
 (26722126, 'M', datetime.timedelta(seconds=40800)),
 (26173805, 'M', datetime.timedelta(seconds=42660)),
 (22228639, 'F', datetime.timedelta(seconds=43380)),
 (22502504, 'M', datetime.timedelta(seconds=50040)),
 (27494880, 'M', datetime.timedelta(seconds=51480)),
 (24096336, 'M', datetime.timedelta(seconds=53640)),
 (25561728, 'M', datetime.timedelta(seconds=56580)),
 (20900955, 'M', datetime.timedelta(seconds=56700)),
 (24470193, 'M', datetime.timedelta(seconds=65400)),
 (20846853, 'F', datetime.timedelta(seconds=65580)),
 (22595853, 'F', datetime.timedelta(seconds=67920)),
 (28984460, 'F', datetime.timedelta(seconds=68220)),
 (26549334, 'F', datetime.timedelta(seconds=69120)),
 (29176490, 'M', datetime.timedelta(seconds=70200)),
 (29654498, 'M', datetime.timedelta(seconds=78000)),
 (25559382, 'M', datetime.timedelta(seconds=80760)),
 (21039249, 'M', datetime.timedelta(seconds=82740)),
 (25797028, 'F', datetime.timedelta(seconds=84120)),
 (27125816, 'F', datetime.timedelta(seconds=84360)),
 (24357615, 'M', datetime.timedelta(seconds=85800)),
 (22841357, 'F', datetime.timedelta(days=1, seconds=1320)),
 (21216581, 'M', datetime.timedelta(days=1, seconds=1500)),
 (28723315, 'M', datetime.timedelta(days=1, seconds=6300)),
 (22416954, 'M', datetime.timedelta(days=1, seconds=12480)),
 (28778757, 'F', datetime.timedelta(days=1, seconds=19200)),
 (20457729, 'F', datetime.timedelta(days=1, seconds=20160)),
 (22607171, 'M', datetime.timedelta(days=1, seconds=26880)),
 (27504040, 'F', datetime.timedelta(days=1, seconds=27120)),
 (26739864, 'F', datetime.timedelta(days=1, seconds=32700)),
 (29839885, 'M', datetime.timedelta(days=1, seconds=33300)),
 (26090619, 'F', datetime.timedelta(days=1, seconds=45600)),
 (28477649, 'F', datetime.timedelta(days=1, seconds=45660)),
 (26793610, 'F', datetime.timedelta(days=1, seconds=48180)),
 (25172300, 'F', datetime.timedelta(days=1, seconds=51060)),
 (26842957, 'F', datetime.timedelta(days=1, seconds=54000)),
 (23112364, 'M', datetime.timedelta(days=1, seconds=57120)),
 (23720373, 'F', datetime.timedelta(days=1, seconds=57180)),
 (22187210, 'M', datetime.timedelta(days=1, seconds=58740)),
 (26013492, 'M', datetime.timedelta(days=1, seconds=60480)),
 (22051341, 'F', datetime.timedelta(days=1, seconds=62940)),
 (22942076, 'M', datetime.timedelta(days=1, seconds=63660)),
 (25742920, 'F', datetime.timedelta(days=1, seconds=65160)),
 (22326517, 'F', datetime.timedelta(days=1, seconds=75480)),
 (25260176, 'M', datetime.timedelta(days=1, seconds=80100)),
 (27670224, 'M', datetime.timedelta(days=1, seconds=82200)),
 (22539296, 'F', datetime.timedelta(days=2, seconds=1260)),
 (21322534, 'F', datetime.timedelta(days=2, seconds=6600)),
 (21606243, 'F', datetime.timedelta(days=2, seconds=7860)),
 (27154822, 'M', datetime.timedelta(days=2, seconds=17160)),
 (29079034, 'F', datetime.timedelta(days=2, seconds=19200)),
 (21599196, 'M', datetime.timedelta(days=2, seconds=21120)),
 (29488258, 'F', datetime.timedelta(days=2, seconds=33180)),
 (27327816, 'M', datetime.timedelta(days=2, seconds=34500)),
 (28019404, 'F', datetime.timedelta(days=2, seconds=36960)),
 (29642388, 'M', datetime.timedelta(days=2, seconds=40440)),
 (20790339, 'M', datetime.timedelta(days=2, seconds=45060)),
 (28676446, 'F', datetime.timedelta(days=2, seconds=45600)),
 (27562275, 'M', datetime.timedelta(days=2, seconds=54960)),
 (28108313, 'M', datetime.timedelta(days=2, seconds=58200)),
 (25020332, 'F', datetime.timedelta(day

In [6]:
%%sql
SELECT hadm_id, gender, 
       CASE 
           WHEN EXTRACT(DAY FROM (dischtime::timestamp - admittime::timestamp)) > 0 
           THEN EXTRACT(DAY FROM (dischtime::timestamp - admittime::timestamp)) || ' days, ' || TO_CHAR(dischtime::timestamp - admittime::timestamp, 'HH24:MI:SS')
           ELSE TO_CHAR(dischtime::timestamp - admittime::timestamp, 'HH24:MI:SS')
       END AS duration
FROM hosp.admissions 
JOIN hosp.patients ON hosp.patients.subject_id = hosp.admissions.subject_id 
ORDER BY (dischtime::TIMESTAMP - admittime::TIMESTAMP), hadm_id;

 * postgresql://postgres:***@localhost:5432/db_a1
275 rows affected.


[(22999601, 'F', '01:07:00'),
 (22896692, 'F', '02:18:00'),
 (23199774, 'M', '03:00:00'),
 (21390688, 'F', '03:45:00'),
 (28697806, 'F', '04:43:00'),
 (22380825, 'F', '05:26:00'),
 (25282382, 'F', '07:47:00'),
 (26332470, 'F', '09:54:00'),
 (23143086, 'M', '11:13:00'),
 (28543425, 'F', '11:17:00'),
 (26722126, 'M', '11:20:00'),
 (26173805, 'M', '11:51:00'),
 (22228639, 'F', '12:03:00'),
 (22502504, 'M', '13:54:00'),
 (27494880, 'M', '14:18:00'),
 (24096336, 'M', '14:54:00'),
 (25561728, 'M', '15:43:00'),
 (20900955, 'M', '15:45:00'),
 (24470193, 'M', '18:10:00'),
 (20846853, 'F', '18:13:00'),
 (22595853, 'F', '18:52:00'),
 (28984460, 'F', '18:57:00'),
 (26549334, 'F', '19:12:00'),
 (29176490, 'M', '19:30:00'),
 (29654498, 'M', '21:40:00'),
 (25559382, 'M', '22:26:00'),
 (21039249, 'M', '22:59:00'),
 (25797028, 'F', '23:22:00'),
 (27125816, 'F', '23:26:00'),
 (24357615, 'M', '23:50:00'),
 (22841357, 'F', '1 days, 00:22:00'),
 (21216581, 'M', '1 days, 00:25:00'),
 (28723315, 'M', '1 days, 01:45:00'),
 (22416954, 'M', '1 days, 03:28:00'),
 (28778757, 'F', '1 days, 05:20:00'),
 (20457729, 'F', '1 days, 05:36:00'),
 (22607171, 'M', '1 days, 07:28:00'),
 (27504040, 'F', '1 days, 07:32:00'),
 (26739864, 'F', '1 days, 09:05:00'),
 (29839885, 'M', '1 days, 09:15:00'),
 (26090619, 'F', '1 days, 12:40:00'),
 (28477649, 'F', '1 days, 12:41:00'),
 (26793610, 'F', '1 days, 13:23:00'),
 (25172300, 'F', '1 days, 14:11:00'),
 (26842957, 'F', '1 days, 15:00:00'),
 (23112364, 'M', '1 days, 15:52:00'),
 (23720373, 'F', '1 days, 15:53:00'),
 (22187210, 'M', '1 days, 16:19:00'),
 (26013492, 'M', '1 days, 16:48:00'),
 (22051341, 'F', '1 days, 17:29:00'),
 (22942076, 'M', '1 days, 17:41:00'),
 (25742920, 'F', '1 days, 18:06:00'),
 (22326517, 'F', '1 days, 20:58:00'),
 (25260176, 'M', '1 days, 22:15:00'),
 (27670224, 'M', '1 days, 22:50:00'),
 (22539296, 'F', '2 days, 00:21:00'),
 (21322534, 'F', '2 days, 01:50:00'),
 (21606243, 'F', '2 days, 02:11:00'),
 (27154822, 'M', '2 days, 04:46:00'),
 (29079034, 'F', '2 days, 05:20:00'),
 (21599196, 'M', '2 days, 05:52:00'),
 (29488258, 'F', '2 days, 09:13:00'),
 (27327816, 'M', '2 days, 09:35:00'),
 (28019404, 'F', '2 days, 10:16:00'),
 (29642388, 'M', '2 days, 11:14:00'),
 (20790339, 'M', '2 days, 12:31:00'),
 (28676446, 'F', '2 days, 12:40:00'),
 (27562275, 'M', '2 days, 15:16:00'),
 (28108313, 'M', '2 days, 16:10:00'),
 (25020332, 'F', '2 days, 17:03:00'),
 (20611796, 'M', '2 days, 17:16:00'),
 (22585261, 'M', '2 days, 17:27:00'),
 (26529390, 'F', '2 days, 18:25:00'),
 (22484749, 'F', '2 days, 18:26:00'),
 (28710730, 'F', '2 days, 18:33:00'),
 (22589518, 'M', '2 days, 18:56:00'),
 (20282368, 'F', '2 days, 19:09:00'),
 (27296885, 'F', '2 days, 19:25:00'),
 (29820177, 'M', '2 days, 19:51:00'),
 (20321825, 'F', '2 days, 20:01:00'),
 (28506150, 'F', '2 days, 20:20:00'),
 (27962747, 'F', '2 days, 21:12:00'),
 (29295881, 'F', '2 days, 21:22:00'),
 (25166559, 'M', '2 days, 21:35:00'),
 (27496788, 'M', '2 days, 22:11:00'),
 (28335091, 'M', '2 days, 22:46:00'),
 (25563031, 'F', '2 days, 23:52:00'),
 (21928381, 'M', '3 days, 00:23:00'),
 (25696644, 'F', '3 days, 03:03:00'),
 (20192635, 'F', '3 days, 04:05:00'),
 (24928679, 'F', '3 days, 04:24:00'),
 (21540783, 'F', '3 days, 06:15:00'),
 (20764029, 'M', '3 days, 07:24:00'),
 (20611640, 'F', '3 days, 08:01:00'),
 (27568122, 'F', '3 days, 09:11:00'),
 (28003918, 'F', '3 days, 09:55:00'),
 (22251969, 'F', '3 days, 13:52:00'),
 (21101111, 'M', '3 days, 14:32:00'),
 (29802992, 'F', '3 days, 15:48:00'),
 (26158160, 'M', '3 days, 15:55:00'),
 (27112038, 'M', '3 days, 16:18:00'),
 (26706939, 'F', '3 days, 17:17:00'),
 (24980601, 'M', '3 days, 17:58:00'),
 (24225421, 'F', '3 days, 18:08:00'),
 (29858644, 'M', '3 days, 18:25:00'),
 (22741225, 'M', '3 days, 18:33:00'),
 (25826145, 'M', '3 days, 18:53:00'),
 (22954658, 'M', '3 days, 19:18:00'),
 (28236161, 'M', '3 days, 20:01:00'),
 (28887654, 'M', '3 days, 21:02:00'),
 (29600294, 'M', '3 days, 22:15:00'),
 (23132022, 'M', '3 da

4.  List the number of distinct medications ordered by each valid(non-null) provider.
    
    output columns:  enter_provider_id, count
    
    order by columns: count(descending)

In [61]:
%%sql 
SELECT enter_provider_id, COUNT(DISTINCT medication) AS count
FROM hosp.emar
WHERE enter_provider_id IS NOT NULL
GROUP BY enter_provider_id
ORDER BY count DESC;


 * postgresql://postgres:***@localhost:5432/db_a1
176 rows affected.


[('P59HMC', 61),
 ('P72Q6Q', 38),
 ('P55K9G', 36),
 ('P23RNP', 34),
 ('P48I2W', 34),
 ('P048FQ', 32),
 ('P02FO8', 32),
 ('P82FME', 31),
 ('P929BC', 29),
 ('P70AXR', 27),
 ('P396OU', 27),
 ('P37PK1', 25),
 ('P19B5D', 25),
 ('P95LFF', 24),
 ('P92NCD', 24),
 ('P97D7P', 22),
 ('P39X1Y', 21),
 ('P52HQY', 21),
 ('P44Y6Q', 20),
 ('P78RR9', 20),
 ('P68WAT', 19),
 ('P989UO', 19),
 ('P343CV', 18),
 ('P96DDH', 18),
 ('P81HAW', 18),
 ('P60D1R', 18),
 ('P56E4S', 18),
 ('P564N8', 18),
 ('P43OM5', 18),
 ('P401QD', 17),
 ('P590QQ', 17),
 ('P99GBB', 17),
 ('P91GCX', 16),
 ('P0950Z', 16),
 ('P14CRZ', 16),
 ('P00SP9', 15),
 ('P77JV8', 15),
 ('P545YS', 14),
 ('P04JU1', 14),
 ('P07ESF', 13),
 ('P54TSS', 13),
 ('P62WK5', 13),
 ('P80JBT', 12),
 ('P72F9D', 12),
 ('P57L65', 12),
 ('P22F7Q', 12),
 ('P52GRX', 12),
 ('P9741S', 11),
 ('P65ERT', 11),
 ('P644IV', 11),
 ('P615MZ', 11),
 ('P0903M', 10),
 ('P63M73', 10),
 ('P577GZ', 10),
 ('P58LGA', 10),
 ('P54GSY', 10),
 ('P34RI3', 10),
 ('P98VLM', 9),
 ('P460MJ', 9),
 ('P62PHV', 9),
 ('P29N7T', 9),
 ('P10010', 9),
 ('P25XWF', 8),
 ('P16DSC', 8),
 ('P57P4B', 7),
 ('P112ZK', 7),
 ('P26PKF', 7),
 ('P86HOS', 7),
 ('P851DG', 7),
 ('P32C22', 7),
 ('P06ZVC', 7),
 ('P16BGO', 7),
 ('P985KM', 6),
 ('P40MH7', 6),
 ('P13VY6', 6),
 ('P6180B', 6),
 ('P40BO0', 6),
 ('P8791D', 6),
 ('P91SJ0', 6),
 ('P7356M', 5),
 ('P09FR0', 5),
 ('P59ZQQ', 5),
 ('P41DMZ', 5),
 ('P873VB', 5),
 ('P10RD5', 5),
 ('P287PF', 5),
 ('P02IVL', 5),
 ('P1622F', 5),
 ('P319O0', 4),
 ('P21ZN7', 4),
 ('P14CSQ', 4),
 ('P44L8C', 4),
 ('P46DSO', 4),
 ('P50S81', 4),
 ('P512CU', 4),
 ('P68HY3', 4),
 ('P71SS1', 4),
 ('P73F6Y', 4),
 ('P77EXW', 4),
 ('P939TC', 4),
 ('P93HLC', 4),
 ('P01QR6', 4),
 ('P37BMC', 3),
 ('P07VSC', 3),
 ('P809P1', 3),
 ('P21QT9', 3),
 ('P55SD0', 3),
 ('P78JDR', 3),
 ('P34CTL', 3),
 ('P45IDG', 3),
 ('P96YI2', 3),
 ('P96QWL', 3),
 ('P04I42', 3),
 ('P63M29', 3),
 ('P98P6K', 3),
 ('P16BEX', 3),
 ('P06GOP', 3),
 ('P49B4L', 3),
 ('P66PFT', 3),
 ('P87TQ9', 3),
 ('P12NSH', 3),
 ('P28EV2', 3),
 ('P47B1O', 3),
 ('P50E6E', 3),
 ('P33K2X', 3),
 ('P30RJG', 2),
 ('P46TN9', 2),
 ('P66MOB', 2),
 ('P25DWA', 2),
 ('P68YWN', 2),
 ('P08XFB', 2),
 ('P73JXJ', 2),
 ('P76TQO', 2),
 ('P81G0E', 2),
 ('P32QXB', 2),
 ('P84D5E', 2),
 ('P85W46', 2),
 ('P862IG', 2),
 ('P86J7K', 2),
 ('P27JPU', 2),
 ('P273N8', 2),
 ('P92UW4', 2),
 ('P203KC', 2),
 ('P950JU', 2),
 ('P95HEC', 2),
 ('P95SHA', 2),
 ('P96YH5', 2),
 ('P12199', 2),
 ('P537CG', 2),
 ('P588PH', 1),
 ('P66WSM', 1),
 ('P89255', 1),
 ('P8961G', 1),
 ('P43C99', 1),
 ('P12WW3', 1),
 ('P39QJ9', 1),
 ('P058F2', 1),
 ('P44139', 1),
 ('P41IS6', 1),
 ('P46KLG', 1),
 ('P019KI', 1),
 ('P76PXH', 1),
 ('P769P9', 1),
 ('P07TKV', 1),
 ('P36L35', 1),
 ('P16QQ6', 1),
 ('P11E38', 1),
 ('P17F1M', 1),
 ('P57P3H', 1),
 ('P26WS3', 1),
 ('P202BU', 1),
 ('P53XNU', 1),
 ('P315GE', 1),
 ('P637CV', 1),
 ('P969WG', 0),
 ('P39IDQ', 0)]

5. Find the number of distinct admissions where the reason for the barcode not being present is ‘Barcode Damaged’ and the marital status of the patient is not ‘MARRIED’.
    
    output: count

In [254]:

%%sql 
SELECT COUNT(DISTINCT e.hadm_id) AS count
FROM hosp.emar_detail ed
JOIN hosp.emar e ON ed.emar_id = e.emar_id
JOIN hosp.admissions a ON e.hadm_id = a.hadm_id
WHERE ed.reason_for_no_barcode = 'Barcode Damaged'
AND a.marital_status <> 'MARRIED'
AND a.marital_status IS NOT NULL;

 * postgresql://postgres:***@localhost:5432/db_a1
1 rows affected.


[(53,)]

6. For each patient, count the number of times they have been admitted to ICU(including 0 number of stays).
    
    output columns: subject_id, count
    
    order by columns: count, subject id

In [33]:
%%sql 
SELECT p.subject_id, COALESCE(COUNT(i.stay_id), 0) AS count
FROM hosp.patients p
LEFT JOIN icu.icustays i ON p.subject_id = i.subject_id
GROUP BY p.subject_id
ORDER BY count, p.subject_id;


 * postgresql://postgres:***@localhost:5432/db_a1
100 rows affected.


[(10000032, 1),
 (10001725, 1),
 (10002495, 1),
 (10003046, 1),
 (10004235, 1),
 (10004422, 1),
 (10004457, 1),
 (10004720, 1),
 (10004733, 1),
 (10005348, 1),
 (10005866, 1),
 (10005909, 1),
 (10006580, 1),
 (10007058, 1),
 (10007795, 1),
 (10007818, 1),
 (10007928, 1),
 (10008287, 1),
 (10008454, 1),
 (10009035, 1),
 (10009049, 1),
 (10009628, 1),
 (10010471, 1),
 (10010867, 1),
 (10011398, 1),
 (10012552, 1),
 (10012853, 1),
 (10013049, 1),
 (10014078, 1),
 (10014729, 1),
 (10015272, 1),
 (10016150, 1),
 (10016810, 1),
 (10018328, 1),
 (10018423, 1),
 (10018501, 1),
 (10018845, 1),
 (10019172, 1),
 (10019385, 1),
 (10019568, 1),
 (10019777, 1),
 (10019917, 1),
 (10020306, 1),
 (10020640, 1),
 (10020786, 1),
 (10020944, 1),
 (10021118, 1),
 (10021312, 1),
 (10021666, 1),
 (10022017, 1),
 (10022041, 1),
 (10022281, 1),
 (10022880, 1),
 (10023771, 1),
 (10024043, 1),
 (10025463, 1),
 (10025612, 1),
 (10026354, 1),
 (10026406, 1),
 (10029484, 1),
 (10031404, 1),
 (10032725, 1),
 (10035185, 1),
 (10035631, 1),
 (10036156, 1),
 (10037861, 1),
 (10037975, 1),
 (10038081, 1),
 (10038933, 1),
 (10038992, 1),
 (10038999, 1),
 (10039831, 1),
 (10039997, 1),
 (10040025, 1),
 (10001217, 2),
 (10002930, 2),
 (10005817, 2),
 (10006053, 2),
 (10015860, 2),
 (10018081, 2),
 (10020187, 2),
 (10021487, 2),
 (10021938, 2),
 (10023239, 2),
 (10026255, 2),
 (10027445, 2),
 (10027602, 2),
 (10029291, 2),
 (10031757, 2),
 (10037928, 2),
 (10003400, 3),
 (10015931, 3),
 (10016742, 3),
 (10017492, 3),
 (10019003, 3),
 (10023117, 3),
 (10039708, 3),
 (10002428, 4),
 (10014354, 4),
 (10020740, 5)]

7. For every patient whose ‘dod’ is not null, find their latest ‘hadm_id’.
    
    output columns: subject_id, latest_hadm_id, dod
    
    order by columns: subject_id

In [251]:
%%sql 
SELECT a.subject_id, 
       max(a.hadm_id) AS latest_hadm_id, 
       max(p.dod) as dod
FROM hosp.admissions a
JOIN hosp.patients p ON a.subject_id = p.subject_id
WHERE dod IS NOT NULL
GROUP BY a.subject_id
ORDER BY a.subject_id;


 * postgresql://postgres:***@localhost:5432/db_a1
31 rows affected.


[(10000032, 29079034, '2180-09-09'),
 (10002930, 28697806, '2201-12-24'),
 (10003400, 29483621, '2137-09-02'),
 (10004720, 22081550, '2186-11-17'),
 (10005817, 28661809, '2135-01-19'),
 (10005866, 27167814, '2149-11-21'),
 (10006053, 22942076, '2111-11-15'),
 (10007818, 22987108, '2146-07-12'),
 (10010471, 29842315, '2155-12-07'),
 (10015931, 28157142, '2177-03-29'),
 (10017492, 27672872, '2116-07-05'),
 (10018081, 28861356, '2134-10-28'),
 (10018845, 21101111, '2184-11-22'),
 (10019003, 29279905, '2155-12-03'),
 (10019777, 27738145, '2187-04-29'),
 (10020640, 27984218, '2154-02-04'),
 (10020944, 29974575, '2131-04-28'),
 (10021666, 22756440, '2172-04-19'),
 (10021938, 27154822, '2182-10-16'),
 (10023117, 29858644, '2175-07-20'),
 (10024043, 25561728, '2117-06-26'),
 (10025463, 27327816, '2137-10-09'),
 (10026255, 22059910, '2201-07-13'),
 (10027445, 29163082, '2146-02-09'),
 (10031757, 28477280, '2137-10-31'),
 (10032725, 25177949, '2143-03-30'),
 (10035631, 29654498, '2116-03-12'),
 (10037861, 24540843, '2117-03-24'),
 (10037975, 27617929, '2185-01-22'),
 (10038081, 20755971, '2115-10-12'),
 (10040025, 27996267, '2148-02-07')]

8. List all the ‘pharmacy_id’ which are present in the pharmacy but not written in any prescriptions.
    
    output columns: pharmacy_id
    
    order by columns: pharmacy_id

In [36]:
%%sql
SELECT p.pharmacy_id
FROM hosp.pharmacy p
LEFT JOIN hosp.prescriptions pr ON p.pharmacy_id = pr.pharmacy_id
WHERE pr.pharmacy_id IS NULL
ORDER BY p.pharmacy_id;


 * postgresql://postgres:***@localhost:5432/db_a1
81 rows affected.


[(969542,),
 (8955806,),
 (9677872,),
 (9939592,),
 (11536667,),
 (11684740,),
 (12985979,),
 (14592277,),
 (18607249,),
 (19719710,),
 (20571047,),
 (21001377,),
 (21162037,),
 (21178358,),
 (24507331,),
 (26593208,),
 (26967992,),
 (29889287,),
 (29961424,),
 (30075133,),
 (31112756,),
 (31197577,),
 (31328468,),
 (35044693,),
 (38355471,),
 (38623903,),
 (40235279,),
 (43055810,),
 (44508914,),
 (45705880,),
 (46751879,),
 (48304926,),
 (51234792,),
 (51912443,),
 (53247680,),
 (53634685,),
 (54221649,),
 (55735633,),
 (57035416,),
 (58382538,),
 (58951282,),
 (60263577,),
 (60513872,),
 (60968122,),
 (63946285,),
 (65371428,),
 (65637912,),
 (65978505,),
 (67197788,),
 (67274619,),
 (67763656,),
 (68402759,),
 (68582615,),
 (68648557,),
 (70906844,),
 (74577756,),
 (74646630,),
 (75093409,),
 (75232893,),
 (75630436,),
 (76276866,),
 (81552029,),
 (82872874,),
 (83135217,),
 (84008739,),
 (85760687,),
 (87937306,),
 (88473607,),
 (88705290,),
 (89257075,),
 (91277264,),
 (92502237,),
 (93444310,),
 (93877457,),
 (94068660,),
 (96985060,),
 (97039197,),
 (97636552,),
 (98258427,),
 (99477284,),
 (99733939,)]

9. List all unique ‘icd_code’, ‘icd_version’ values present in both’ diagnoses_icd’ and ‘procedures_icd’ tables.
    
    output columns: icd_code, icd_version
    
    order by columns: icd_code, icd_version

In [46]:
%%sql 
SELECT icd_code, icd_version
FROM hosp.diagnoses_icd

INTERSECT

SELECT icd_code, icd_version
FROM hosp.procedures_icd

ORDER BY icd_code, icd_version;



 * postgresql://postgres:***@localhost:5432/db_a1
2 rows affected.


[('5187', 9), ('9962', 9)]

10. List the unique ‘hcpcs_cd’ and a short description of all hcpcs events related to ‘Hospital observation’. You can assume that an event is related to x if its description contains x(case-insensitive).
    
    output columns: hcpcs_cd, short_description
    
    order by columns: hcpcs_cd, short_description

In [47]:
%%sql
SELECT DISTINCT hcpcs_cd, short_description
FROM hosp.hcpcsevents
WHERE LOWER(short_description) LIKE '%hospital observation%'
ORDER BY hcpcs_cd, short_description;


 * postgresql://postgres:***@localhost:5432/db_a1
3 rows affected.


[('99218', 'Hospital observation services'),
 ('99219', 'Hospital observation services'),
 ('G0378', 'Hospital observation per hr')]

## Intermediate Queries

1. For each patient who has a non-NULL value in the ‘dod (date of death)
column, write an SQL query to find the ‘hadm_id corresponding to their
earliest ‘admittime.
COL362/632 DBMS Assignment 1 SQL Queries 29
output columns: subject_id, hadm_id, dod
order by columns: subject_id

In [82]:
%%sql
SELECT p.subject_id, 
       a.hadm_id AS hadm_id, 
       p.dod
FROM hosp.patients p
JOIN hosp.admissions a ON p.subject_id = a.subject_id
WHERE p.dod IS NOT NULL
AND TO_TIMESTAMP(a.admittime, 'YYYY-MM-DD HH24:MI:SS') = (
    SELECT MIN(TO_TIMESTAMP(admittime, 'YYYY-MM-DD HH24:MI:SS'))
    FROM hosp.admissions
    WHERE subject_id = p.subject_id
)
ORDER BY p.subject_id;


 * postgresql://postgres:***@localhost:5432/db_a1
31 rows affected.


[(10000032, 22595853, '2180-09-09'),
 (10002930, 22380825, '2201-12-24'),
 (10003400, 26090619, '2137-09-02'),
 (10004720, 22081550, '2186-11-17'),
 (10005817, 20626031, '2135-01-19'),
 (10005866, 26158160, '2149-11-21'),
 (10006053, 22942076, '2111-11-15'),
 (10007818, 22987108, '2146-07-12'),
 (10010471, 21322534, '2155-12-07'),
 (10015931, 28157142, '2177-03-29'),
 (10017492, 27672872, '2116-07-05'),
 (10018081, 21027282, '2134-10-28'),
 (10018845, 21101111, '2184-11-22'),
 (10019003, 28003918, '2155-12-03'),
 (10019777, 27738145, '2187-04-29'),
 (10020640, 27984218, '2154-02-04'),
 (10020944, 29974575, '2131-04-28'),
 (10021666, 22756440, '2172-04-19'),
 (10021938, 23112364, '2182-10-16'),
 (10023117, 29839885, '2175-07-20'),
 (10024043, 25561728, '2117-06-26'),
 (10025463, 27327816, '2137-10-09'),
 (10026255, 20437651, '2201-07-13'),
 (10027445, 26275841, '2146-02-09'),
 (10031757, 28477280, '2137-10-31'),
 (10032725, 25177949, '2143-03-30'),
 (10035631, 29462354, '2116-03-12'),
 (10037861, 24256866, '2117-03-24'),
 (10037975, 27617929, '2185-01-22'),
 (10038081, 20755971, '2115-10-12'),
 (10040025, 27125816, '2148-02-07')]

In [7]:
%%sql
select a.subject_id, b.hadm_id, a.dod 
from hosp.patients a join hosp.admissions b on a.subject_id=b.subject_id  
where dod is not NULL 
and b.admittime=(select min(sub.admittime) from hosp.admissions sub where sub.subject_id=b.subject_id)
order by a.subject_id;

 * postgresql://postgres:***@localhost:5432/db_a1
31 rows affected.


[(10000032, 22595853, '2180-09-09'),
 (10002930, 22380825, '2201-12-24'),
 (10003400, 26090619, '2137-09-02'),
 (10004720, 22081550, '2186-11-17'),
 (10005817, 20626031, '2135-01-19'),
 (10005866, 26158160, '2149-11-21'),
 (10006053, 22942076, '2111-11-15'),
 (10007818, 22987108, '2146-07-12'),
 (10010471, 21322534, '2155-12-07'),
 (10015931, 28157142, '2177-03-29'),
 (10017492, 27672872, '2116-07-05'),
 (10018081, 21027282, '2134-10-28'),
 (10018845, 21101111, '2184-11-22'),
 (10019003, 28003918, '2155-12-03'),
 (10019777, 27738145, '2187-04-29'),
 (10020640, 27984218, '2154-02-04'),
 (10020944, 29974575, '2131-04-28'),
 (10021666, 22756440, '2172-04-19'),
 (10021938, 23112364, '2182-10-16'),
 (10023117, 29839885, '2175-07-20'),
 (10024043, 25561728, '2117-06-26'),
 (10025463, 27327816, '2137-10-09'),
 (10026255, 20437651, '2201-07-13'),
 (10027445, 26275841, '2146-02-09'),
 (10031757, 28477280, '2137-10-31'),
 (10032725, 25177949, '2143-03-30'),
 (10035631, 29462354, '2116-03-12'),
 (10037861, 24256866, '2117-03-24'),
 (10037975, 27617929, '2185-01-22'),
 (10038081, 20755971, '2115-10-12'),
 (10040025, 27125816, '2148-02-07')]

2. Find the average duration of admissions(HHMMSS or X days, HHMMSS
having diagnosis icd_code=4019 and icd_version=9. Admission duration is
defined as the difference between dischtime and admittime.
output columns: avg_duration

In [49]:
%%sql
SELECT JUSTIFY_INTERVAL(AVG(TO_TIMESTAMP(a.dischtime, 'YYYY-MM-DD HH24:MI:SS') - 
                            TO_TIMESTAMP(a.admittime, 'YYYY-MM-DD HH24:MI:SS'))) 
       AS avg_duration
FROM hosp.admissions a
JOIN hosp.diagnoses_icd d ON a.hadm_id = d.hadm_id
WHERE d.icd_code = '4019' AND d.icd_version = 9
AND a.dischtime IS NOT NULL;


 * postgresql://postgres:***@localhost:5432/db_a1
1 rows affected.


[(datetime.timedelta(days=7, seconds=17813, microseconds=823530),)]

In [8]:
%%sql
SELECT AVG(duration) as avg_duration from
    (select a.hadm_id, a.dischtime::TIMESTAMP - a.admittime::TIMESTAMP as duration, d.icd_code as icd_code, d.icd_version as icd_version  
    from hosp.admissions a join hosp.diagnoses_icd d on a.subject_id=d.subject_id and a.hadm_id=d.hadm_id 
    where d.icd_code='4019' and d.icd_version='9' and a.dischtime is not NULL and a.admittime is not NULL) 
AS subquery;

 * postgresql://postgres:***@localhost:5432/db_a1
1 rows affected.


[(datetime.timedelta(days=7, seconds=17813, microseconds=823530),)]


3. For each caregiver_id, find the number of procedure events, chart events, and
date-time events, documented by that caregiver.
output columns: caregiver_id, procedureevents_count, chartevents_count,
datetimeevents_count
order by columns: caregiver_id, procedureevents_count, chartevents_count,
datetimeevents_count

In [ ]:
%%sql
SELECT c.caregiver_id, 
       COALESCE(p.procedureevents_count, 0) AS procedureevents_count,
       COALESCE(ch.chartevents_count, 0) AS chartevents_count,
       COALESCE(d.datetimeevents_count, 0) AS datetimeevents_count
FROM icu.caregiver AS c
LEFT JOIN (
    SELECT caregiver_id, COUNT(*) AS procedureevents_count
    FROM icu.procedureevents
    GROUP BY caregiver_id
) AS p ON p.caregiver_id = c.caregiver_id
LEFT JOIN (
    SELECT caregiver_id, COUNT(*) AS chartevents_count
    FROM icu.chartevents
    GROUP BY caregiver_id
) AS ch ON ch.caregiver_id = c.caregiver_id
LEFT JOIN (
    SELECT caregiver_id, COUNT(*) AS datetimeevents_count
    FROM icu.datetimeevents
    GROUP BY caregiver_id
) AS d ON d.caregiver_id = c.caregiver_id
ORDER BY c.caregiver_id, procedureevents_count, chartevents_count, datetimeevents_count;


In [ ]:
%%sql
WITH procedure_events AS (
    SELECT caregiver_id, COUNT(*) AS procedure_count
    FROM icu.procedureevents 
    GROUP BY caregiver_id
),
chart_events AS (
    SELECT caregiver_id, COUNT(*) AS chart_count
    FROM icu.chartevents
    GROUP BY caregiver_id
),
datetime_events as (
    SELECT caregiver_id, COUNT(*) AS datetime_count
    FROM icu.datetimeevents
    GROUP BY caregiver_id
)

SELECT 
    cg.caregiver_id AS caregiver_id, 
    COALESCE(p.procedure_count, 0) AS procedureevents_count,
    COALESCE(c.chart_count, 0) AS chartevents_count,
    COALESCE(d.datetime_count, 0) AS datetimeevents_count
FROM icu.caregiver cg 
left join procedure_events p 
on p.caregiver_id = cg.caregiver_id
left JOIN chart_events c 
    ON c.caregiver_id = cg.caregiver_id
left JOIN datetime_events d
    ON d.caregiver_id = cg.caregiver_id
    order by caregiver_id, procedureevents_count, chartevents_count, datetimeevents_count;




4. Find out if any patient has been diagnosed with an ‘infection in multiple
admissions in the same year(on the basis of admission time). You can assume
that the title of such a diagnosis with contain the word ‘infection (case
insensitive).
output columns: subject_id, count_admissions, year
order by columns: year, count_admissions(descending)

In [83]:
%%sql
SELECT d.subject_id, 
       COUNT(DISTINCT a.hadm_id) AS count_admissions, 
       EXTRACT(YEAR FROM TO_TIMESTAMP(a.admittime, 'YYYY-MM-DD HH24:MI:SS')) AS year
FROM hosp.admissions a
JOIN hosp.diagnoses_icd d ON a.hadm_id = d.hadm_id
JOIN hosp.d_icd_diagnoses di ON d.icd_code = di.icd_code
WHERE LOWER(di.long_title) LIKE '%infection%'
GROUP BY d.subject_id, year
HAVING COUNT(DISTINCT a.hadm_id) > 1
ORDER BY year, count_admissions DESC, subject_id;


 * postgresql://postgres:***@localhost:5432/db_a1
16 rows affected.


[(10035631, 3, Decimal('2112')),
 (10021487, 4, Decimal('2117')),
 (10018081, 2, Decimal('2134')),
 (10003400, 2, Decimal('2137')),
 (10005866, 4, Decimal('2149')),
 (10019003, 3, Decimal('2155')),
 (10002428, 3, Decimal('2156')),
 (10001217, 2, Decimal('2157')),
 (10015931, 2, Decimal('2176')),
 (10016742, 2, Decimal('2178')),
 (10037928, 2, Decimal('2178')),
 (10037928, 2, Decimal('2179')),
 (10000032, 3, Decimal('2180')),
 (10015860, 2, Decimal('2192')),
 (10002930, 2, Decimal('2193')),
 (10002930, 3, Decimal('2197'))]

In [11]:
%%sql

WITH yearly_admissions AS (
    SELECT 
        hosp.admissions.subject_id, 
        hosp.admissions.hadm_id, 
        hosp.admissions.admittime, 
        hosp.diagnoses_icd.icd_code, 
        hosp.diagnoses_icd.icd_version, 
        hosp.d_icd_diagnoses.long_title
    FROM 
        hosp.admissions 
    JOIN 
        hosp.diagnoses_icd 
        ON hosp.admissions.subject_id = hosp.diagnoses_icd.subject_id 
        AND hosp.admissions.hadm_id = hosp.diagnoses_icd.hadm_id 
    JOIN 
        hosp.d_icd_diagnoses 
        ON hosp.diagnoses_icd.icd_code = hosp.d_icd_diagnoses.icd_code
    WHERE 
        LOWER(hosp.d_icd_diagnoses.long_title) LIKE '%infection%' 
),
patient_admission_counts AS (
    SELECT 
        subject_id, 
        COUNT(DISTINCT hadm_id) AS count_admissions, 
        DATE_PART('year', TO_TIMESTAMP(admittime, 'YYYY-MM-DD HH24:MI:SS'))::INTEGER as year
    FROM 
        yearly_admissions
    GROUP BY 
        subject_id, year
    HAVING 
        COUNT(DISTINCT hadm_id) > 1 
)
SELECT *
FROM 
    patient_admission_counts
ORDER BY 
    year, count_admissions DESC, subject_id;

 * postgresql://postgres:***@localhost:5432/db_a1
16 rows affected.


[(10035631, 3, 2112),
 (10021487, 4, 2117),
 (10018081, 2, 2134),
 (10003400, 2, 2137),
 (10005866, 4, 2149),
 (10019003, 3, 2155),
 (10002428, 3, 2156),
 (10001217, 2, 2157),
 (10015931, 2, 2176),
 (10016742, 2, 2178),
 (10037928, 2, 2178),
 (10037928, 2, 2179),
 (10000032, 3, 2180),
 (10015860, 2, 2192),
 (10002930, 2, 2193),
 (10002930, 3, 2197)]

5. List all the patients who had an admission type of ‘URGENT and died in the
same admission(use hospital_expire_flag). Find how many ICD procedures
were ordered and how many diagnoses were recorded for that patient in that
admission.
output columns: subject_id, hadm_id, count_procedures, count_diagnoses
order by columns: subject_id, hadm_id, count_procedures(descending),
count_diagnoses(descending)


In [53]:
%%sql
SELECT a.subject_id, 
       a.hadm_id, 
       COUNT(DISTINCT p.icd_code) AS count_procedures, 
       COUNT(DISTINCT d.icd_code) AS count_diagnoses
FROM hosp.admissions a
LEFT JOIN hosp.procedures_icd p ON a.hadm_id = p.hadm_id
LEFT JOIN hosp.diagnoses_icd d ON a.hadm_id = d.hadm_id
WHERE a.admission_type = 'URGENT' 
AND a.hospital_expire_flag = 1
GROUP BY a.subject_id, a.hadm_id
ORDER BY a.subject_id, a.hadm_id, count_procedures DESC, count_diagnoses DESC;


 * postgresql://postgres:***@localhost:5432/db_a1
5 rows affected.


[(10003400, 23559586, 11, 38),
 (10006053, 22942076, 3, 10),
 (10015931, 22130791, 8, 23),
 (10037975, 27617929, 3, 22),
 (10038081, 20755971, 8, 38)]

In [12]:
%%sql
WITH 
tmp1 AS (
    SELECT subject_id, hadm_id 
    FROM hosp.admissions 
    WHERE admission_type = 'URGENT' AND hospital_expire_flag = 1
),
tmp2 AS (
    SELECT subject_id, hadm_id, COUNT(*) AS count_diagnoses 
    FROM hosp.diagnoses_icd 
    GROUP BY subject_id, hadm_id
),
tmp3 AS (
    SELECT subject_id, hadm_id, COUNT(*) AS count_procedures 
    FROM hosp.procedures_icd 
    GROUP BY subject_id, hadm_id
)
SELECT distinct
    t1.subject_id, 
    t1.hadm_id, 
    COALESCE(t3.count_procedures, 0) AS count_procedures, 
    COALESCE(t2.count_diagnoses, 0) AS count_diagnoses
FROM 
    tmp1 AS t1
LEFT JOIN 
    tmp2 AS t2
ON 
    t1.subject_id = t2.subject_id AND t1.hadm_id = t2.hadm_id
LEFT JOIN 
    tmp3 AS t3
ON 
    t1.subject_id = t3.subject_id AND t1.hadm_id = t3.hadm_id
ORDER BY 
    t1.subject_id, 
    t1.hadm_id, 
    count_procedures DESC, 
    count_diagnoses DESC;

 * postgresql://postgres:***@localhost:5432/db_a1
5 rows affected.


[(10003400, 23559586, 12, 38),
 (10006053, 22942076, 3, 10),
 (10015931, 22130791, 9, 23),
 (10037975, 27617929, 3, 22),
 (10038081, 20755971, 9, 38)]

6. Find the average BMI (kg/m2 of patients who were prescribed the
medications ‘OxyCODONE Immediate Release) and ‘Insulin both (case
sensitive). [Hint - use hosp.omr table]
output columns: avg_BMI

In [182]:
%%sql
SELECT CAST(AVG(CAST(result_value AS DOUBLE PRECISION)) AS DECIMAL(12,10)) AS avg_BMI
FROM hosp.omr
WHERE result_name = 'BMI (kg/m2)' 
AND subject_id IN (
    SELECT DISTINCT subject_id
    FROM hosp.prescriptions
    WHERE drug = 'Insulin'
    INTERSECT
    SELECT subject_id
    FROM hosp.prescriptions
    WHERE drug = 'OxyCODONE (Immediate Release)'
);


 * postgresql://postgres:***@localhost:5432/db_a1
1 rows affected.


[(Decimal('29.4908309456'),)]

In [13]:
%%sql
 with tmp1 as (select subject_id, CAST(result_value AS DECIMAL) as bmi from hosp.omr where result_name='BMI (kg/m2)'),
tmp2 as (select distinct subject_id from hosp.pharmacy where medication ='OxyCODONE (Immediate Release)'),
tmp3 as (select distinct subject_id from hosp.pharmacy where medication ='Insulin'),
tmp4 AS (
    SELECT subject_id 
    FROM tmp2
    INTERSECT
    SELECT subject_id 
    FROM tmp3
)
SELECT  CAST(AVG(tmp1.bmi) AS DECIMAL(20,10)) AS avg_BMI
FROM 
    tmp1 
INNER JOIN 
    tmp4 
ON 
    tmp1.subject_id = tmp4.subject_id;

 * postgresql://postgres:***@localhost:5432/db_a1
1 rows affected.


[(Decimal('29.4908309456'),)]

7. Find the patients who had the same diagnoses when they were admitted for
the first time and most recently(use admittime). Find the percentage
distribution of these patients on the basis of their gender. Round off to 2
decimal places.
output columns: gender, percentage
order by columns: percentage(descending)

In [46]:
%%sql
WITH FirstLastDiagnosis AS (
    SELECT d.subject_id,
           d.hadm_id,
           icd.icd_code,
           icd.icd_version,
           icd.long_title AS diagnosis_title,
           a.admittime,
           RANK() OVER (PARTITION BY d.subject_id ORDER BY a.admittime ASC) AS first_rank,
           RANK() OVER (PARTITION BY d.subject_id ORDER BY a.admittime DESC) AS last_rank
    FROM hosp.diagnoses_icd d
    JOIN hosp.admissions a ON d.hadm_id = a.hadm_id
    JOIN hosp.d_icd_diagnoses icd 
        ON d.icd_code = icd.icd_code 
        AND d.icd_version = icd.icd_version
),
FirstDiagnosis AS (
    SELECT subject_id, 
           ARRAY_AGG(DISTINCT diagnosis_title ORDER BY diagnosis_title) AS diagnosis_set
    FROM FirstLastDiagnosis
    WHERE first_rank = 1
    GROUP BY subject_id
),
LastDiagnosis AS (
    SELECT subject_id, 
           ARRAY_AGG(DISTINCT diagnosis_title ORDER BY diagnosis_title) AS diagnosis_set
    FROM FirstLastDiagnosis
    WHERE last_rank = 1
    GROUP BY subject_id
),
MatchingPatients AS (
    SELECT p.subject_id, p.gender
    FROM FirstDiagnosis f
    JOIN LastDiagnosis l ON f.subject_id = l.subject_id
    JOIN hosp.patients p ON f.subject_id = p.subject_id
    WHERE EXISTS (
    SELECT 1 
    FROM unnest(f.diagnosis_set) AS first_diag
    JOIN unnest(l.diagnosis_set) AS last_diag 
    ON first_diag = last_diag
    )
),
SelectedCounts AS (
    SELECT gender, COUNT(*) AS selected_count
    FROM MatchingPatients
    GROUP BY gender
),
TotalSelected AS (
    SELECT SUM(selected_count) AS total_selected
    FROM SelectedCounts
)
SELECT sc.gender, 
       ROUND(100.0 * sc.selected_count / ts.total_selected, 2) AS percentage
FROM SelectedCounts sc
JOIN TotalSelected ts ON true
ORDER BY percentage DESC;


 * postgresql://postgres:***@localhost:5432/db_a1
2 rows affected.


[('M', Decimal('58.62')), ('F', Decimal('41.38'))]

In [14]:
%%sql
with 
tmp1 as( select subject_id, min(admittime) as first_adm, max(admittime) as last_adm from hosp.admissions group by subject_id), 
diagnoses_match AS (
    SELECT 
        tmp1.subject_id
    FROM tmp1 
    JOIN hosp.diagnoses_icd di1
        ON tmp1.subject_id = di1.subject_id
    JOIN hosp.diagnoses_icd di2
        ON tmp1.subject_id = di2.subject_id
    WHERE di1.hadm_id = (SELECT hadm_id FROM hosp.admissions WHERE subject_id = tmp1.subject_id AND admittime = tmp1.first_adm)
      AND di2.hadm_id = (SELECT hadm_id FROM hosp.admissions WHERE subject_id = tmp1.subject_id AND admittime = tmp1.last_adm)
      AND di1.icd_code = di2.icd_code
      AND di1.icd_version = di2.icd_version
),
tmp6 as (select diagnoses_match.subject_id, hosp.patients.gender from diagnoses_match join hosp.patients on diagnoses_match.subject_id=hosp.patients.subject_id)
SELECT 
    gender,
    ROUND(COUNT(distinct subject_id) * 100.0 / SUM(COUNT(distinct subject_id)) OVER (), 2) AS percentage
FROM 
    tmp6
GROUP BY 
    gender
ORDER BY percentage DESC;

 * postgresql://postgres:***@localhost:5432/db_a1
2 rows affected.


[('M', Decimal('59.74')), ('F', Decimal('40.26'))]

8. Calculate the average admission duration of hospital stays (HHMMSS or X
days, HHMMSS for patients across all unique admissions. Admission
duration is defined as the difference between dischtime and admittime.
output columns: subject_id, avg_duration
order by columns: subject_id

In [56]:
%%sql
SELECT a.subject_id, 
       JUSTIFY_INTERVAL(AVG(TO_TIMESTAMP(a.dischtime, 'YYYY-MM-DD HH24:MI:SS') - 
                            TO_TIMESTAMP(a.admittime, 'YYYY-MM-DD HH24:MI:SS'))) 
       AS avg_duration
FROM hosp.admissions a
WHERE a.dischtime IS NOT NULL
GROUP BY a.subject_id
ORDER BY a.subject_id;


 * postgresql://postgres:***@localhost:5432/db_a1
100 rows affected.


[(10000032, datetime.timedelta(days=1, seconds=38400)),
 (10001217, datetime.timedelta(days=6, seconds=30630)),
 (10001725, datetime.timedelta(days=2, seconds=85920)),
 (10002428, datetime.timedelta(days=5, seconds=53674, microseconds=285714)),
 (10002495, datetime.timedelta(days=6, seconds=77040)),
 (10002930, datetime.timedelta(days=3, seconds=28330)),
 (10003046, datetime.timedelta(days=7, seconds=16680)),
 (10003400, datetime.timedelta(days=11, seconds=63677, microseconds=142857)),
 (10004235, datetime.timedelta(days=5, seconds=26540)),
 (10004422, datetime.timedelta(days=10, seconds=300)),
 (10004457, datetime.timedelta(days=1, seconds=70010)),
 (10004720, datetime.timedelta(days=5, seconds=1740)),
 (10004733, datetime.timedelta(days=23, seconds=9120)),
 (10005348, datetime.timedelta(days=5, seconds=3440)),
 (10005817, datetime.timedelta(days=12, seconds=18090)),
 (10005866, datetime.timedelta(days=8, seconds=35194, microseconds=285714)),
 (10005909, datetime.timedelta(days=4, seconds=57780)),
 (10006053, datetime.timedelta(days=1, seconds=63660)),
 (10006580, datetime.timedelta(days=5, seconds=8700)),
 (10007058, datetime.timedelta(days=3, seconds=69480)),
 (10007795, datetime.timedelta(days=8, seconds=20628)),
 (10007818, datetime.timedelta(days=31, seconds=26580)),
 (10007928, datetime.timedelta(days=5, seconds=66540)),
 (10008287, datetime.timedelta(days=4, seconds=44280)),
 (10008454, datetime.timedelta(days=10, seconds=33720)),
 (10009035, datetime.timedelta(days=4, seconds=23400)),
 (10009049, datetime.timedelta(days=5, seconds=21240)),
 (10009628, datetime.timedelta(days=7, seconds=72720)),
 (10010471, datetime.timedelta(days=3, seconds=39120)),
 (10010867, datetime.timedelta(days=7, seconds=45600)),
 (10011398, datetime.timedelta(days=4, seconds=22920)),
 (10012552, datetime.timedelta(days=7, seconds=75120)),
 (10012853, datetime.timedelta(days=2, seconds=79550)),
 (10013049, datetime.timedelta(days=4, seconds=23400)),
 (10014078, datetime.timedelta(days=4, seconds=56340)),
 (10014354, datetime.timedelta(days=4, seconds=19005)),
 (10014729, datetime.timedelta(days=8, seconds=6870)),
 (10015272, datetime.timedelta(days=5, seconds=76140)),
 (10015860, datetime.timedelta(days=6, seconds=22047, microseconds=692308)),
 (10015931, datetime.timedelta(days=10, seconds=64800)),
 (10016150, datetime.timedelta(days=5, seconds=17040)),
 (10016742, datetime.timedelta(days=3, seconds=63160)),
 (10016810, datetime.timedelta(days=5, seconds=51840)),
 (10017492, datetime.timedelta(days=11, seconds=21750)),
 (10018081, datetime.timedelta(days=13, seconds=41205)),
 (10018328, datetime.timedelta(days=6, seconds=50460)),
 (10018423, datetime.timedelta(days=7, seconds=55980)),
 (10018501, datetime.timedelta(days=5, seconds=70320)),
 (10018845, datetime.timedelta(days=3, seconds=52320)),
 (10019003, datetime.timedelta(days=7, seconds=61890)),
 (10019172, datetime.timedelta(days=4, seconds=62580)),
 (10019385, datetime.timedelta(days=6, seconds=18990)),
 (10019568, datetime.timedelta(days=2, seconds=66780)),
 (10019777, datetime.timedelta(days=16, seconds=66300)),
 (10019917, datetime.timedelta(days=2, seconds=62820)),
 (10020187, datetime.timedelta(days=5, seconds=50880)),
 (10020306, datetime.timedelta(days=8, seconds=14580)),
 (10020640, datetime.timedelta(days=7, seconds=48600)),
 (10020740, datetime.timedelta(days=10, seconds=36876)),
 (10020786, datetime.timedelta(days=4, seconds=16500)),
 (10020944, datetime.timedelta(days=14, seconds=5220)),
 (10021118, datetime.timedelta(days=7, seconds=71400)),
 (10021312, datetime.timedelta(days=5, seconds=37830)),
 (10021487, datetime.timedelta(days=12, seconds=30580)),
 (10021666, datetime.timedelta(days=10, seconds=57180)),
 (10021938, datetime.timedelta(days=1, seconds=80340)),
 (10022017, datetime.timedelta(days=6, seconds=54000)),
 (10022041, datetime.timedelta(days=5, seconds=720)),
 (10022281, datetime.timedelta(days=2, seconds=40440)),
 (10022880, datetime.timedelta(days=7, seconds=2

In [15]:
%%sql
with tmp1 as( select subject_id, hadm_id, (dischtime::timestamp - admittime::timestamp) as duration from hosp.admissions where dischtime is not NULL)
select subject_id, avg(duration) from tmp1 group by subject_id order by subject_id;

 * postgresql://postgres:***@localhost:5432/db_a1
100 rows affected.


[(10000032, datetime.timedelta(days=1, seconds=38400)),
 (10001217, datetime.timedelta(days=6, seconds=30630)),
 (10001725, datetime.timedelta(days=2, seconds=85920)),
 (10002428, datetime.timedelta(days=5, seconds=53674, microseconds=285714)),
 (10002495, datetime.timedelta(days=6, seconds=77040)),
 (10002930, datetime.timedelta(days=3, seconds=28330)),
 (10003046, datetime.timedelta(days=7, seconds=16680)),
 (10003400, datetime.timedelta(days=11, seconds=63677, microseconds=142857)),
 (10004235, datetime.timedelta(days=5, seconds=26540)),
 (10004422, datetime.timedelta(days=10, seconds=300)),
 (10004457, datetime.timedelta(days=1, seconds=70010)),
 (10004720, datetime.timedelta(days=5, seconds=1740)),
 (10004733, datetime.timedelta(days=23, seconds=9120)),
 (10005348, datetime.timedelta(days=5, seconds=3440)),
 (10005817, datetime.timedelta(days=12, seconds=18090)),
 (10005866, datetime.timedelta(days=8, seconds=35194, microseconds=285714)),
 (10005909, datetime.timedelta(days=4, seconds=57780)),
 (10006053, datetime.timedelta(days=1, seconds=63660)),
 (10006580, datetime.timedelta(days=5, seconds=8700)),
 (10007058, datetime.timedelta(days=3, seconds=69480)),
 (10007795, datetime.timedelta(days=8, seconds=20628)),
 (10007818, datetime.timedelta(days=31, seconds=26580)),
 (10007928, datetime.timedelta(days=5, seconds=66540)),
 (10008287, datetime.timedelta(days=4, seconds=44280)),
 (10008454, datetime.timedelta(days=10, seconds=33720)),
 (10009035, datetime.timedelta(days=4, seconds=23400)),
 (10009049, datetime.timedelta(days=5, seconds=21240)),
 (10009628, datetime.timedelta(days=7, seconds=72720)),
 (10010471, datetime.timedelta(days=3, seconds=39120)),
 (10010867, datetime.timedelta(days=7, seconds=45600)),
 (10011398, datetime.timedelta(days=4, seconds=22920)),
 (10012552, datetime.timedelta(days=7, seconds=75120)),
 (10012853, datetime.timedelta(days=2, seconds=79550)),
 (10013049, datetime.timedelta(days=4, seconds=23400)),
 (10014078, datetime.timedelta(days=4, seconds=56340)),
 (10014354, datetime.timedelta(days=4, seconds=19005)),
 (10014729, datetime.timedelta(days=8, seconds=6870)),
 (10015272, datetime.timedelta(days=5, seconds=76140)),
 (10015860, datetime.timedelta(days=6, seconds=22047, microseconds=692308)),
 (10015931, datetime.timedelta(days=10, seconds=64800)),
 (10016150, datetime.timedelta(days=5, seconds=17040)),
 (10016742, datetime.timedelta(days=3, seconds=63160)),
 (10016810, datetime.timedelta(days=5, seconds=51840)),
 (10017492, datetime.timedelta(days=11, seconds=21750)),
 (10018081, datetime.timedelta(days=13, seconds=41205)),
 (10018328, datetime.timedelta(days=6, seconds=50460)),
 (10018423, datetime.timedelta(days=7, seconds=55980)),
 (10018501, datetime.timedelta(days=5, seconds=70320)),
 (10018845, datetime.timedelta(days=3, seconds=52320)),
 (10019003, datetime.timedelta(days=7, seconds=61890)),
 (10019172, datetime.timedelta(days=4, seconds=62580)),
 (10019385, datetime.timedelta(days=6, seconds=18990)),
 (10019568, datetime.timedelta(days=2, seconds=66780)),
 (10019777, datetime.timedelta(days=16, seconds=66300)),
 (10019917, datetime.timedelta(days=2, seconds=62820)),
 (10020187, datetime.timedelta(days=5, seconds=50880)),
 (10020306, datetime.timedelta(days=8, seconds=14580)),
 (10020640, datetime.timedelta(days=7, seconds=48600)),
 (10020740, datetime.timedelta(days=10, seconds=36876)),
 (10020786, datetime.timedelta(days=4, seconds=16500)),
 (10020944, datetime.timedelta(days=14, seconds=5220)),
 (10021118, datetime.timedelta(days=7, seconds=71400)),
 (10021312, datetime.timedelta(days=5, seconds=37830)),
 (10021487, datetime.timedelta(days=12, seconds=30580)),
 (10021666, datetime.timedelta(days=10, seconds=57180)),
 (10021938, datetime.timedelta(days=1, seconds=80340)),
 (10022017, datetime.timedelta(days=6, seconds=54000)),
 (10022041, datetime.timedelta(days=5, seconds=720)),
 (10022281, datetime.timedelta(days=2, seconds=40440)),
 (10022880, datetime.timedelta(days=7, seconds=2

9. List the patients who were prescribed the same medication (same
pharmacy_id) multiple times. List their ‘subject_id in the order(descending) of
the number of times a medication was prescribed to the same patient. If the
count is same, order by subject_id, pharmacy_id.
output columns: subject_id, pharmacy_id

In [ ]:
%%sql
SELECT subject_id, pharmacy_id
FROM hosp.prescriptions
GROUP BY subject_id, pharmacy_id
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC, subject_id, pharmacy_id;


In [ ]:
%%sql
with tmp1 as 
    (select subject_id, pharmacy_id, count(hadm_id) 
    from hosp.prescriptions 
    group by subject_id, pharmacy_id  
    having count(hadm_id)>1 )
select subject_id, pharmacy_id 
from tmp1 
order by count desc, subject_id, pharmacy_id;

10. List the patients who were diagnosed with a kidney disease in their first
admission and readmitted after this diagnoses. You can assume that the long
title of such a diagnosis will contain the word ‘kidney(case insensitive). List
the 100 patients who were admitted most recently(based on the ‘admittime of
their first admission)
output columns: subject_id
order by columns: subject_id

In [104]:
%%sql
WITH first_admissions AS (
    SELECT a.subject_id,  min(a.admittime) as admittime
    FROM hosp.admissions a
    JOIN hosp.diagnoses_icd d ON a.subject_id = d.subject_id
    JOIN hosp.d_icd_diagnoses di ON d.icd_code = di.icd_code
    AND d.icd_version = di.icd_version
    WHERE LOWER(di.long_title) LIKE '%kidney%'
    GROUP BY a.subject_id
    ORDER BY admittime desc
)
SELECT DISTINCT a.subject_id
FROM hosp.admissions a
JOIN first_admissions f ON a.subject_id = f.subject_id
WHERE a.admittime > f.admittime
ORDER BY a.subject_id
LIMIT 100;


 * postgresql://postgres:***@localhost:5432/db_a1
28 rows affected.


[(10002428,),
 (10003400,),
 (10004235,),
 (10005817,),
 (10010471,),
 (10012853,),
 (10014354,),
 (10015860,),
 (10015931,),
 (10016742,),
 (10017492,),
 (10018081,),
 (10019003,),
 (10020306,),
 (10020740,),
 (10021487,),
 (10021938,),
 (10023117,),
 (10023239,),
 (10024043,),
 (10032725,),
 (10035631,),
 (10037861,),
 (10037928,),
 (10038992,),
 (10039708,),
 (10039997,),
 (10040025,)]

In [18]:
%%sql
with first_adm as (
    select subject_id, MIN(admittime) as min_admittime
    from hosp.admissions
    group by subject_id
), kidney_pat as (
    select distinct adm.subject_id, adm.admittime
    from hosp.admissions adm
    join first_adm on adm.subject_id = first_adm.subject_id and adm.admittime = first_adm.min_admittime
     join hosp.diagnoses_icd diag on adm.hadm_id = diag.hadm_id
     join hosp.d_icd_diagnoses d_icd on diag.icd_code = d_icd.icd_code and diag.icd_version = d_icd.icd_version
    where lower(long_title) LIKE '%kidney%'
), tmp as (select distinct a.subject_id, kidney_pat.admittime from hosp.admissions a join kidney_pat on a.subject_id=kidney_pat.subject_id and a.admittime>kidney_pat.admittime order by kidney_pat.admittime desc limit 100)
select subject_id from tmp order by subject_id ;

 * postgresql://postgres:***@localhost:5432/db_a1
13 rows affected.


[(10004235,),
 (10010471,),
 (10012853,),
 (10015931,),
 (10016742,),
 (10018081,),
 (10020740,),
 (10021487,),
 (10021938,),
 (10032725,),
 (10037861,),
 (10038992,),
 (10040025,)]

## Advanced Queries

1. Find patients whose diagnoses (from `diagnoses_icd`) changed across at least three admissions, where the set of diagnoses(`icd_code`) in each admission is different from those in another admission or their prescribed medications (from `prescriptions`) must have changed (based on the set of drug names) at least three times between admissions. 
    
    output columns: subject_id, total_admissions, num_distinct_diagnoses_set_count, num_distinct_medications_set_count
    order by columns: total_admissions DESC, num_distinct_diagnoses_set_count DESC, subject_id ASC

In [108]:
%%sql
WITH patient_drug_diagnosis AS (
    SELECT 
        a.subject_id,
        a.hadm_id,
        ARRAY_REMOVE(ARRAY_AGG(DISTINCT p.drug ORDER BY p.drug), NULL) AS medications,
        ARRAY_REMOVE(ARRAY_AGG(DISTINCT d.icd_code ORDER BY d.icd_code), NULL) AS diagnoses
    FROM 
        hosp.admissions a
    LEFT JOIN 
        hosp.prescriptions p ON a.hadm_id = p.hadm_id
    LEFT JOIN 
        hosp.diagnoses_icd d ON a.hadm_id = d.hadm_id
    GROUP BY 
        a.subject_id, a.hadm_id
)
SELECT
    subject_id,
    COUNT(DISTINCT hadm_id) AS total_admissions,
    COUNT(DISTINCT diagnoses) AS num_distinct_diagnoses_set_count,
    COUNT(DISTINCT medications) AS num_distinct_medications_set_count
FROM 
    patient_drug_diagnosis
GROUP BY 
    subject_id
HAVING 
    COUNT(DISTINCT diagnoses) >= 3 
    OR COUNT(DISTINCT medications) >= 3
ORDER BY 
    total_admissions DESC,
    num_distinct_diagnoses_set_count DESC,
    subject_id ASC;


 * postgresql://postgres:***@localhost:5432/db_a1
28 rows affected.


[(10014354, 20, 20, 18),
 (10015860, 13, 13, 13),
 (10002930, 12, 12, 6),
 (10037928, 10, 10, 9),
 (10039708, 10, 10, 9),
 (10040025, 10, 10, 10),
 (10035631, 9, 9, 9),
 (10019003, 8, 8, 8),
 (10002428, 7, 7, 7),
 (10003400, 7, 7, 7),
 (10005866, 7, 7, 7),
 (10023117, 7, 7, 7),
 (10004457, 6, 6, 6),
 (10012853, 6, 6, 6),
 (10021487, 6, 6, 6),
 (10007795, 5, 5, 5),
 (10020740, 5, 5, 4),
 (10000032, 4, 4, 4),
 (10018081, 4, 4, 4),
 (10004235, 3, 3, 3),
 (10005348, 3, 3, 3),
 (10010867, 3, 3, 3),
 (10015931, 3, 3, 3),
 (10016742, 3, 3, 3),
 (10020306, 3, 3, 3),
 (10023239, 3, 3, 3),
 (10027445, 3, 3, 3),
 (10039997, 3, 3, 3)]

2. Identify patients (along with `hadm_no` ) who had `microbiologyevents`  indicating resistance to at least two different antibiotics (`micro_specimen_id`) within a single hospital admission, with the antibiotics marked as 'R' (`interpretation`) in the `microbiologyevents` table. Additionally, check if these patients were later transferred to the ICU(`icustays`) during that hospital stay, calculate their total ICU length of stay in hours(upto 2 decimal places) for that admission. If a patient did not have an ICU stay, set the ICU length of stay to 0. Ensure to handle only valid admissions (i.e., non-null `hadm_id` , if `hadm_id` is null then do not include in answer) and check whether the patient experienced in-hospital mortality in that admission by verifying if the `discharge_location` field is marked as 'DIED'. Output the 1 if patient died else 0.
    
    Output columns: subject_id, hadm_id, resistant_antibiotic_count, icu_length_of_stay_hours, and died_in_hospital.
    
    ordered by columns: died_in_hospital(descending),  resistant_antibiotic_count(descending) ,icu_length_of_stay_hours(descending), subject_id(ascending), hadm_id(ascending).

In [123]:
%%sql
WITH resistant_patients AS (
    SELECT subject_id, 
    hadm_id, 
    COUNT(DISTINCT micro_specimen_id) AS resistant_antibiotic_count
    
    FROM hosp.microbiologyevents
    
    WHERE interpretation = 'R' AND hadm_id IS NOT NULL
    GROUP BY subject_id, hadm_id
    HAVING COUNT(DISTINCT micro_specimen_id) >= 2
),
icu_stay AS (
    SELECT subject_id,
        hadm_id, 
            CASE
                WHEN icu.hadm_id is null THEN 0
                ELSE round(
                    extract(
                        epoch
                        from (icu.outtime::timestamp - icu.intime::timestamp)
                    ) / 3600.0,
                    2
                )
        END as icu_length_of_stay_hours
    FROM icu.icustays as icu
    GROUP BY subject_id, hadm_id, icu.outtime, icu.intime
)
SELECT r.subject_id, 
    r.hadm_id, 
    r.resistant_antibiotic_count, 
    COALESCE(i.icu_length_of_stay_hours, 0) AS icu_length_of_stay_hours, 
    CASE WHEN a.discharge_location = 'DIED' THEN 1 ELSE 0 END AS died_in_hospital
FROM resistant_patients r
LEFT JOIN icu_stay i ON r.subject_id = i.subject_id AND r.hadm_id = i.hadm_id
JOIN hosp.admissions a ON r.hadm_id = a.hadm_id
ORDER BY died_in_hospital DESC, 
        resistant_antibiotic_count DESC, 
        icu_length_of_stay_hours DESC, 
        r.subject_id, 
        r.hadm_id;


 * postgresql://postgres:***@localhost:5432/db_a1
6 rows affected.


[(10007818, 22987108.0, 2, Decimal('492.69'), 1),
 (10027602, 28166872.0, 3, Decimal('318.20'), 0),
 (10014729, 23300884.0, 3, Decimal('0'), 0),
 (10020944, 29974575.0, 2, Decimal('217.84'), 0),
 (10040025, 27996267.0, 2, Decimal('156.91'), 0),
 (10015860, 24698912.0, 2, Decimal('15.41'), 0)]

3. Find patients who underwent multiple(more than one) distinct procedures(`icd_code`) from `procedures_icd` for any admission and were also diagnosed with `icd_code` starting with "T81" from `diagnoses_icd` in any admission. From those selected, find out who has the higher-than-or-equal to the average number of transfers per admission among themselves.
    
        output columns: subject_id, distinct_procedures_count, average_transfers
        
        order by columns: average_transfers(Descending), distinct_procedures_count (Descending),  subject_id (Ascending)

In [23]:
%%sql
WITH procedure_counts AS (
    SELECT subject_id, hadm_id, COUNT(DISTINCT icd_code) AS distinct_procedures_count
    FROM hosp.procedures_icd
    WHERE hadm_id IS NOT NULL 
    AND subject_id IS NOT NULL
    GROUP BY subject_id, hadm_id
    HAVING COUNT(DISTINCT icd_code) > 1
),
diagnosed_patients AS (
    SELECT DISTINCT subject_id, hadm_id
    FROM hosp.diagnoses_icd
    WHERE icd_code LIKE 'T81%' 
    AND hadm_id IS NOT NULL 
    AND subject_id IS NOT NULL
),
selected_transfers AS (
    SELECT t.subject_id, t.hadm_id, COUNT(*) AS num_transfers
    FROM hosp.transfers t
    JOIN procedure_counts p ON t.subject_id = p.subject_id AND t.hadm_id = p.hadm_id
    JOIN diagnosed_patients d ON t.subject_id = d.subject_id AND t.hadm_id = d.hadm_id
    GROUP BY t.subject_id, t.hadm_id
),
avg_transfers AS (
    SELECT AVG(num_transfers) AS avg_transfers_per_admission 
    FROM selected_transfers
)
SELECT p.subject_id, 
       p.distinct_procedures_count,
       CAST(t.num_transfers AS DOUBLE PRECISION) AS num_transfers
FROM procedure_counts p
JOIN diagnosed_patients d ON p.subject_id = d.subject_id AND p.hadm_id = d.hadm_id
JOIN selected_transfers t ON p.subject_id = t.subject_id AND p.hadm_id = t.hadm_id
WHERE t.num_transfers >= (SELECT avg_transfers_per_admission FROM avg_transfers)
ORDER BY num_transfers DESC, p.distinct_procedures_count DESC, p.subject_id;



 * postgresql://postgres:***@localhost:5432/db_a1
3 rows affected.


[(10003400, 11, 7.0), (10040025, 5, 6.0), (10015931, 2, 5.0)]

4. Find the patient having the longest chain of `transfers` for an admission(`hadm_id`). For that patient output all the chains of transfers for each hospital admission. If more than one patient has the longest chain output them all. 
    
    output columns: subject_id, hadm_id, [transfers]
    
    order by: len([transfers]) Ascending, hadm_id (Ascending), subject_id (Ascending)

In [25]:
%%sql
WITH TransferChains AS (
    SELECT hadm_id, subject_id, 
           array_agg(transfer_id ORDER BY intime) AS transfers,
           COUNT(*) AS chain_length
    FROM hosp.transfers
    WHERE hadm_id IS NOT NULL
    GROUP BY hadm_id, subject_id
),
MaxChain AS (
    SELECT chain_length
    FROM TransferChains
    ORDER BY chain_length DESC
    LIMIT 1
),
MaxChainAdmissions AS (
    SELECT hadm_id, subject_id
    FROM TransferChains
    WHERE chain_length = (SELECT chain_length FROM MaxChain)
),
RelevantAdmissions AS (
    SELECT DISTINCT t.hadm_id, t.subject_id
    FROM MaxChainAdmissions m
    JOIN hosp.transfers t ON m.subject_id = t.subject_id
    WHERE t.hadm_id IS NOT NULL
)
SELECT r.subject_id, r.hadm_id, 
       COALESCE(array_to_string(tc.transfers, ','), '') AS "[transfers]"
FROM RelevantAdmissions r
LEFT JOIN TransferChains tc ON r.hadm_id = tc.hadm_id
WHERE r.hadm_id IS NOT NULL
ORDER BY array_length(transfers, 1), r.hadm_id, r.subject_id;


 * postgresql://postgres:***@localhost:5432/db_a1
17 rows affected.


[(10020740, 29820177.0, '37979587,30902573'),
 (10020740, 23143086.0, '39169528,39039080,39997902'),
 (10020740, 23199774.0, '39930808,37667580,37321690'),
 (10002428, 25797028.0, '39764235,33133642,32611769'),
 (10002428, 26549334.0, '38216551,38451756,37119417'),
 (10002428, 28295257.0, '37376268,39142928,36902988'),
 (10020740, 25826145.0, '32145159,38089431,33082837,33110494'),
 (10014729, 28889419.0, '32206630,33558396,30201349,36847815'),
 (10002428, 20321825.0, '32822973,34807493,39544317,35150464,38874094'),
 (10002428, 23473524.0, '33978784,35479615,39816752,30896594,38628705'),
 (10017492, 27672872.0, '35175702,36090371,34147183,34958043,38022582,33321869'),
 (10002428, 28676446.0, '34982171,36994100,34854504,36857297,31088796,31949882,31868350,32665319'),
 (10008454, 20291550.0, '39284197,39742220,33457312,37573895,31959184,37646708,32625081,37921160,38711513,37062479'),
 (10014729, 23300884.0, '37887480,37471901,35959158,34953924,31954553,34411721,35226146,38564981,33082827,33058230'),
 (10020740, 23831430.0, '35026312,30733321,35044342,32995805,35889503,37253871,31077365,34002407,34492498,33240146'),
 (10017492, 27417763.0, '38213541,31838375,30901670,39543480,35562584,36035031,34139123,32758321,36871784,37907801'),
 (10002428, 28662225.0, '32007337,38519116,37824512,33987268,32875370,38875437,30025354,38277070,31606213,37069433')]

5. Find patients - admission pair whose at least one `procedure_icd`  has `icd_code` starts with "0", "1", or "2". Keep the patient - admission if they received medications the same day or the next day of any procedure (for the same admission). Ensure that patients receive at least two different types of medications(`drug`) during their entire hospital stay. Calculate the time gap, use the same format as `prescriptions.starttime` between the first procedure and the last medication prescription(assume the procedure took place at midnight) of the admission, determine the number of distinct `icd_codes` from diagnoses_icd and find the number of distinct `procedures` (`icd_code`) they have gone through during the admission. 
    
    Output Columns: subject_id, hadm_id, distinct_diagnoses,  distinct_procedures, time_gap
    
    Order By: distinct_diagnoses (Descending), distinct_procedures (Descending), time_gap (Ascending), subject_id (Ascending), hadm_id(Ascending)

In [29]:
%%sql
WITH Procedures AS (
    SELECT DISTINCT p.subject_id, p.hadm_id, p.icd_code, p.icd_version, a.admittime, p.chartdate
    FROM hosp.procedures_icd p
    JOIN hosp.admissions a ON p.hadm_id = a.hadm_id
    WHERE (p.icd_code LIKE '0%' OR p.icd_code LIKE '1%' OR p.icd_code LIKE '2%')
      AND p.subject_id IS NOT NULL AND p.hadm_id IS NOT NULL
),
Medications AS (
    SELECT DISTINCT pr.subject_id, pr.hadm_id, pr.drug, pr.starttime::timestamp
    FROM hosp.prescriptions pr
    WHERE pr.hadm_id IS NOT NULL AND pr.subject_id IS NOT NULL
),
ValidAdmissions AS (
    SELECT DISTINCT proc.subject_id, proc.hadm_id, proc.chartdate
    FROM Procedures proc
    JOIN Medications med ON proc.hadm_id = med.hadm_id
    WHERE med.starttime::date BETWEEN proc.chartdate::date AND proc.chartdate::date + INTERVAL '1 day'
      AND proc.hadm_id IS NOT NULL AND proc.subject_id IS NOT NULL
),
DistinctMedications AS (
    SELECT subject_id, hadm_id, COUNT(DISTINCT drug) AS med_count
    FROM Medications
    WHERE hadm_id IS NOT NULL AND subject_id IS NOT NULL
    GROUP BY subject_id, hadm_id
    HAVING COUNT(DISTINCT drug) >= 2
),
FinalAdmissions AS (
    SELECT v.subject_id, v.hadm_id, v.chartdate
    FROM ValidAdmissions v
    JOIN DistinctMedications dm ON v.subject_id = dm.subject_id AND v.hadm_id = dm.hadm_id
),
TimeGap AS (
    SELECT f.subject_id, f.hadm_id, 
           TO_CHAR(
               age(MAX(med.starttime), MIN(f.chartdate::timestamp)), 
               'YYYY-MM-DD HH24:MI:SS'
           ) AS time_gap
    FROM FinalAdmissions f
    JOIN Medications med ON f.subject_id = med.subject_id AND f.hadm_id = med.hadm_id
    GROUP BY f.subject_id, f.hadm_id
),
DistinctCounts AS (
    SELECT f.subject_id, f.hadm_id, 
           COUNT(DISTINCT diag.icd_code) AS distinct_diagnoses,
           COUNT(DISTINCT proc.icd_code) AS distinct_procedures
    FROM FinalAdmissions f
    JOIN hosp.diagnoses_icd diag ON f.subject_id = diag.subject_id AND f.hadm_id = diag.hadm_id
    JOIN hosp.procedures_icd proc ON f.subject_id = proc.subject_id AND f.hadm_id = proc.hadm_id
    GROUP BY f.subject_id, f.hadm_id
)
SELECT DISTINCT d.subject_id, d.hadm_id, d.distinct_diagnoses, d.distinct_procedures, t.time_gap
FROM DistinctCounts d
JOIN TimeGap t ON d.subject_id = t.subject_id AND d.hadm_id = t.hadm_id
ORDER BY d.distinct_diagnoses DESC, d.distinct_procedures DESC, t.time_gap ASC, d.subject_id ASC, d.hadm_id ASC;



 * postgresql://postgres:***@localhost:5432/db_a1
89 rows affected.


[(10007818, 22987108, 39, 18, '0000-01-01 18:00:00'),
 (10037861, 24540843, 39, 8, '0000-00-11 00:00:00'),
 (10029291, 22205327, 39, 8, '0000-00-17 22:00:00'),
 (10040025, 27996267, 39, 5, '0000-00-12 20:00:00'),
 (10014354, 29757856, 39, 1, '0000-00-05 17:00:00'),
 (10039708, 28258130, 38, 15, '0000-01-03 16:00:00'),
 (10003400, 23559586, 38, 11, '0000-00-23 14:00:00'),
 (10038081, 20755971, 38, 8, '0000-00-03 15:00:00'),
 (10035631, 29276678, 36, 8, '0000-00-12 02:00:00'),
 (10015860, 24698912, 33, 7, '0000-00-15 09:00:00'),
 (10019777, 27738145, 31, 19, '0000-00-15 12:00:00'),
 (10023117, 21133938, 30, 5, '0000-00-09 08:00:00'),
 (10040025, 27259207, 30, 3, '0000-00-13 22:00:00'),
 (10040025, 27876215, 30, 2, '0000-00-04 09:00:00'),
 (10015931, 28157142, 30, 2, '0000-00-07 20:00:00'),
 (10019003, 26529390, 29, 5, '0000-00-02 10:00:00'),
 (10004720, 22081550, 29, 4, '0000-00-05 15:00:00'),
 (10005866, 20364112, 28, 8, '0000-00-24 15:00:00'),
 (10020306, 23052851, 28, 4, '0000-00-16 20:00:00'),
 (10014354, 22508257, 28, 3, '0000-00-07 11:00:00'),
 (10015931, 24420677, 27, 1, '0000-00-09 16:00:00'),
 (10023117, 21607814, 27, 1, '0000-00-12 20:00:00'),
 (10010867, 22429197, 26, 10, '0000-00-10 10:00:00'),
 (10039708, 25864431, 26, 7, '0000-00-12 17:00:00'),
 (10002495, 24982426, 26, 6, '0000-00-08 08:00:00'),
 (10019003, 29279905, 26, 3, '0000-00-10 06:00:00'),
 (10005817, 28661809, 25, 6, '0000-00-15 18:00:00'),
 (10039708, 24928679, 25, 2, '0000-00-01 20:00:00'),
 (10019003, 27525946, 24, 8, '0000-00-07 08:00:00'),
 (10040025, 25933959, 24, 3, '0000-00-10 22:00:00'),
 (10035631, 21476294, 24, 3, '0000-00-28 08:00:00'),
 (10019003, 26703331, 24, 2, '0000-00-01 14:00:00'),
 (10014354, 27487226, 24, 1, '0000-00-07 08:00:00'),
 (10015931, 22130791, 23, 8, '0000-00-04 14:00:00'),
 (10039708, 23819016, 21, 1, '0000-00-05 08:00:00'),
 (10019003, 21457723, 21, 1, '0000-00-07 20:00:00'),
 (10015860, 28196804, 20, 4, '0000-00-00 15:00:00'),
 (10015860, 22413744, 20, 1, '0000-00-07 16:00:00'),
 (10005866, 27167814, 18, 6, '0000-00-11 18:00:00'),
 (10016742, 28506150, 18, 3, '0000-00-00 22:00:00'),
 (10035631, 20385771, 18, 3, '0000-00-21 08:00:00'),
 (10038999, 27189241, 17, 9, '0000-00-10 09:00:00'),
 (10027602, 28166872, 17, 9, '0000-00-20 16:00:00'),
 (10021312, 28829452, 17, 8, '0000-00-06 18:00:00'),
 (10015860, 25103777, 17, 5, '0000-00-06 15:00:00'),
 (10037928, 24225421, 17, 3, '0000-00-03 14:00:00'),
 (10038992, 24745425, 17, 2, '0000-00-04 22:00:00'),
 (10025612, 23403708, 16, 10, '0000-00-07 12:00:00'),
 (10018328, 23786647, 16, 2, '0000-00-08 17:00:00'),
 (10022017, 22342963, 15, 4, '0000-00-05 21:00:00'),
 (10023239, 21759936, 15, 3, '0000-00-03 17:00:00'),
 (10019003, 25508812, 15, 2, '0000-00-01 13:00:00'),
 (10015860, 26352758, 15, 2, '0000-00-04 15:00:00'),
 (10031404, 21606243, 15, 1, '0000-00-03 08:00:00'),
 (10021118, 24490144, 12, 4, '0000-00-04 08:00:00'),
 (10010867, 22950920, 12, 1, '0000-00-03 14:00:00'),
 (10018845, 21101111, 12, 1, '0000-00-03 15:00:00'),
 (10021312, 25020332, 11, 7, '0000-00-02 17:00:00'),
 (10016742, 27568122, 11, 4, '0000-00-03 08:00:00'),
 (10014354, 28335091, 11, 2, '0000-00-01 08:00:00'),
 (10010867, 22196214, 11, 1, '0000-00-02 11:00:00'),
 (10004235, 25970245, 10, 6, '0000-00-05 16:00:00'),
 (10025463, 24470193, 10, 4, '0000-00-01 20:00:00'),
 (10027602, 21477991, 10, 4, '0000-00-02 20:00:00'),
 (10004457, 28108313, 10, 3, '0000-00-02 10:00:00'),
 (10001217, 24597018, 10, 3, '0000-00-04 12:00:00'),
 (10019172, 21540783, 10, 2, '0000-00-02 19:00:00'),
 (10018423, 29366372, 9, 10, '0000-00-07 08:00:00'),
 (10039997, 24294180, 9, 2, '0000-00-04 08:00:00'),
 (10019385, 20297618, 9, 2, '0000-00-04 14:00:00'),
 (10040025, 27125816, 9, 2, '0000-00-05 10:00:00'),
 (10005866, 22589518, 9, 1, '0000-00-00 14:00:00'),
 (10020187, 26842957, 9, 1, '0000-00-01 20:00:00'),
 (10017492, 27672872, 9, 1, '0000-00-07 16:00:00'),
 (10004457, 21039249, 8, 6, '0000-00-00 20:00:00'),
 (10014729, 28889419, 8, 6

6. Identify ICU patients for whom the difference between fluid input and output during a stay (`stayid`)exceeds 2 liters (2000 mL). Consider the input and output events for which the amount is recorded in milliliters (`ml`).
    
    For these patients, retrieve all distinct `item_id` associated with `inputevents` and `outputevents`, along with the corresponding abbreviations for each ICU stay. In each row under the input_or_output column write ‘input’ if it's taken from `inputevent`, or ‘output’ if it's taken from `outputevent`
    
    Output columns subject_id, stay_id, item_id, input_or_output, description
    
    Ordered by: subject_id (Ascending) and stay_id (Ascending), item_id (Ascending) , input_or_output (Ascending).

In [261]:
%%sql
WITH FluidBalance AS (
    SELECT ie.subject_id, ie.stay_id,
           COALESCE(SUM(ie.amount), 0) AS total_input,
           COALESCE(SUM(oe.value), 0) AS total_output
    FROM icu.inputevents ie
    LEFT JOIN icu.outputevents oe ON ie.stay_id = oe.stay_id
    WHERE ie.amountuom = 'ml' AND oe.valueuom = 'ml'
    GROUP BY ie.subject_id, ie.stay_id
    HAVING ABS(COALESCE(SUM(ie.amount), 0) - COALESCE(SUM(oe.value), 0)) > 2000
),
DistinctItems AS (
    SELECT fb.subject_id, fb.stay_id, ie.itemid AS item_id, 'input' AS input_or_output
    FROM FluidBalance fb
    JOIN icu.inputevents ie ON fb.stay_id = ie.stay_id
    WHERE ie.amountuom = 'ml'
    
    UNION
    
    SELECT fb.subject_id, fb.stay_id, oe.itemid AS item_id, 'output' AS input_or_output
    FROM FluidBalance fb
    JOIN icu.outputevents oe ON fb.stay_id = oe.stay_id
    WHERE oe.valueuom = 'ml'
)
SELECT di.subject_id, di.stay_id, di.item_id, di.input_or_output, d_items.label AS description
FROM DistinctItems di
JOIN icu.d_items d_items ON di.item_id = d_items.itemid
ORDER BY di.subject_id ASC, di.stay_id ASC, di.item_id ASC, di.input_or_output ASC;




 * postgresql://postgres:***@localhost:5432/db_a1
1443 rows affected.


[(10001217, 34592300, 220949, 'input', 'Dextrose 5%'),
 (10001217, 34592300, 225158, 'input', 'NaCl 0.9%'),
 (10001217, 34592300, 226089, 'input', 'Piggyback'),
 (10001217, 34592300, 226452, 'input', 'PO Intake'),
 (10001217, 34592300, 226560, 'output', 'Void'),
 (10001217, 34592300, 227523, 'input', 'Magnesium Sulfate (Bolus)'),
 (10001217, 37067082, 220949, 'input', 'Dextrose 5%'),
 (10001217, 37067082, 225158, 'input', 'NaCl 0.9%'),
 (10001217, 37067082, 226089, 'input', 'Piggyback'),
 (10001217, 37067082, 226452, 'input', 'PO Intake'),
 (10001217, 37067082, 226560, 'output', 'Void'),
 (10001217, 37067082, 226571, 'output', 'Emesis'),
 (10001725, 31205490, 225158, 'input', 'NaCl 0.9%'),
 (10001725, 31205490, 225944, 'input', 'Sterile Water'),
 (10001725, 31205490, 226361, 'input', 'Pre-Admission/Non-ICU Intake'),
 (10001725, 31205490, 226452, 'input', 'PO Intake'),
 (10001725, 31205490, 226559, 'output', 'Foley'),
 (10002428, 33987268, 220949, 'input', 'Dextrose 5%'),
 (10002428, 33987268, 225158, 'input', 'NaCl 0.9%'),
 (10002428, 33987268, 225797, 'input', 'Free Water'),
 (10002428, 33987268, 225828, 'input', 'LR'),
 (10002428, 33987268, 226089, 'input', 'Piggyback'),
 (10002428, 33987268, 226361, 'input', 'Pre-Admission/Non-ICU Intake'),
 (10002428, 33987268, 226452, 'input', 'PO Intake'),
 (10002428, 33987268, 226559, 'output', 'Foley'),
 (10002428, 33987268, 226580, 'output', 'Fecal Bag'),
 (10002428, 33987268, 226583, 'output', 'Rectal Tube'),
 (10002428, 33987268, 226633, 'output', 'Pre-Admission'),
 (10002428, 33987268, 227523, 'input', 'Magnesium Sulfate (Bolus)'),
 (10002428, 34807493, 220864, 'input', 'Albumin 5%'),
 (10002428, 34807493, 220949, 'input', 'Dextrose 5%'),
 (10002428, 34807493, 225158, 'input', 'NaCl 0.9%'),
 (10002428, 34807493, 225799, 'input', 'Gastric Meds'),
 (10002428, 34807493, 225930, 'input', 'Peptamen 1.5 (Full)'),
 (10002428, 34807493, 226452, 'input', 'PO Intake'),
 (10002428, 34807493, 226453, 'input', 'GT Flush'),
 (10002428, 34807493, 226559, 'output', 'Foley'),
 (10002428, 34807493, 226583, 'output', 'Rectal Tube'),
 (10002428, 34807493, 226633, 'output', 'Pre-Admission'),
 (10002428, 35479615, 220949, 'input', 'Dextrose 5%'),
 (10002428, 35479615, 225158, 'input', 'NaCl 0.9%'),
 (10002428, 35479615, 225168, 'input', 'Packed Red Blood Cells'),
 (10002428, 35479615, 225799, 'input', 'Gastric Meds'),
 (10002428, 35479615, 225930, 'input', 'Peptamen 1.5 (Full)'),
 (10002428, 35479615, 225943, 'input', 'Solution'),
 (10002428, 35479615, 226089, 'input', 'Piggyback'),
 (10002428, 35479615, 226452, 'input', 'PO Intake'),
 (10002428, 35479615, 226453, 'input', 'GT Flush'),
 (10002428, 35479615, 226559, 'output', 'Foley'),
 (10002428, 35479615, 226579, 'output', 'Stool'),
 (10002428, 35479615, 226583, 'output', 'Rectal Tube'),
 (10002428, 35479615, 228135, 'input', 'Isosource 1.5 (Full)'),
 (10002428, 38875437, 220862, 'input', 'Albumin 25%'),
 (10002428, 38875437, 220864, 'input', 'Albumin 5%'),
 (10002428, 38875437, 220949, 'input', 'Dextrose 5%'),
 (10002428, 38875437, 225158, 'input', 'NaCl 0.9%'),
 (10002428, 38875437, 225799, 'input', 'Gastric Meds'),
 (10002428, 38875437, 225828, 'input', 'LR'),
 (10002428, 38875437, 225916, 'input', 'TPN w/ Lipids'),
 (10002428, 38875437, 225917, 'input', 'TPN without Lipids'),
 (10002428, 38875437, 225934, 'input', 'Vivonex (Full)'),
 (10002428, 38875437, 225943, 'input', 'Solution'),
 (10002428, 38875437, 226089, 'input', 'Piggyback'),
 (10002428, 38875437, 226452, 'input', 'PO Intake'),
 (10002428, 38875437, 226453, 'input', 'GT Flush'),
 (10002428, 38875437, 226559, 'output', 'Foley'),
 (10002428, 38875437, 226579, 'output', 'Stool'),
 (10002428, 38875437, 226580, 'output', 'Fecal Bag'),
 (10002428, 38875437, 226588, 'output', 'Chest Tube #1'),
 (10002428, 38875437, 226619, 'output', 'Pigtail #1'),
 (10002428, 38875437, 227522, 'input', 'KCL (Bolus)'),
 (10002428, 38875437, 227523, 'input', 'Magnesium Sulfate (Bolus)'),
 (10002495, 36753294, 2209

7. Identify patients diagnosed with `icd_code` starting with "E10" or "E11" during their admission and also diagnosed with `icd_code` starting with "N18" in the same or subsequent admission. For all these patients give the distinct icd_codes for diagnoses (from `diagnoses_icd`) and the distinct icd_codes for procedures (from `procedures_icd`) for each admission. Also if the `icd_code` belongs to procedures then output ‘procedures’ else output ‘diagnoses’   
    
    output columns: subject_id, admission_id, diagnoses_or_procedure, icd_code
    
    ordered by : subject_id (Ascending), admission_id (Ascending), icd_code, diagnoses_or_procedure(Ascending)

In [38]:
%%sql
WITH E10_E11_Patients AS (
    SELECT DISTINCT d.subject_id, d.hadm_id, a.admittime,
           LEAD(d.hadm_id) OVER (PARTITION BY d.subject_id ORDER BY a.admittime) AS next_hadm_id
    FROM hosp.diagnoses_icd d
    JOIN hosp.admissions a ON d.hadm_id = a.hadm_id
    WHERE d.icd_code LIKE 'E10%' OR d.icd_code LIKE 'E11%'
),
N18_Patients AS (
    SELECT DISTINCT d.subject_id, d.hadm_id
    FROM hosp.diagnoses_icd d
    WHERE d.icd_code LIKE 'N18%'
),
LinkedAdmissions AS (
    SELECT e.subject_id, e.hadm_id AS admission_id
    FROM E10_E11_Patients e
    JOIN N18_Patients n 
    ON e.subject_id = n.subject_id
    AND (e.hadm_id = n.hadm_id OR e.next_hadm_id = n.hadm_id)
),
Diagnoses AS (
    SELECT DISTINCT d.subject_id, d.hadm_id AS admission_id, d.icd_code, 'diagnoses' AS diagnoses_or_procedure
    FROM hosp.diagnoses_icd d
    JOIN LinkedAdmissions la ON d.subject_id = la.subject_id
),
Procedures AS (
    SELECT DISTINCT p.subject_id, p.hadm_id AS admission_id, p.icd_code, 'procedures' AS diagnoses_or_procedure
    FROM hosp.procedures_icd p
    JOIN LinkedAdmissions la ON p.subject_id = la.subject_id
)
SELECT subject_id, admission_id, diagnoses_or_procedure, icd_code
FROM (
    SELECT * FROM Diagnoses
    UNION
    SELECT * FROM Procedures
) AS combined_results
ORDER BY subject_id ASC, admission_id ASC, icd_code ASC, diagnoses_or_procedure ASC;





 * postgresql://postgres:***@localhost:5432/db_a1
1404 rows affected.


[(10005817, 20626031, 'diagnoses', '04110'),
 (10005817, 20626031, 'diagnoses', '25000'),
 (10005817, 20626031, 'diagnoses', '27800'),
 (10005817, 20626031, 'diagnoses', '2859'),
 (10005817, 20626031, 'diagnoses', '3051'),
 (10005817, 20626031, 'diagnoses', '30981'),
 (10005817, 20626031, 'procedures', '3612'),
 (10005817, 20626031, 'procedures', '3615'),
 (10005817, 20626031, 'procedures', '3961'),
 (10005817, 20626031, 'diagnoses', '4019'),
 (10005817, 20626031, 'diagnoses', '41071'),
 (10005817, 20626031, 'diagnoses', '41401'),
 (10005817, 20626031, 'diagnoses', '4240'),
 (10005817, 20626031, 'diagnoses', '42731'),
 (10005817, 20626031, 'diagnoses', '42732'),
 (10005817, 20626031, 'diagnoses', '4280'),
 (10005817, 20626031, 'diagnoses', '4400'),
 (10005817, 20626031, 'diagnoses', '496'),
 (10005817, 20626031, 'diagnoses', '5990'),
 (10005817, 20626031, 'diagnoses', '71690'),
 (10005817, 20626031, 'diagnoses', '7847'),
 (10005817, 20626031, 'diagnoses', 'V1006'),
 (10005817, 20626031, 'diagnoses', 'V153'),
 (10005817, 20626031, 'diagnoses', 'V4582'),
 (10005817, 20626031, 'diagnoses', 'V5863'),
 (10005817, 20626031, 'diagnoses', 'V5866'),
 (10005817, 20626031, 'diagnoses', 'V707'),
 (10005817, 20626031, 'diagnoses', 'V8531'),
 (10005817, 20626031, 'diagnoses', 'V8741'),
 (10005817, 28661809, 'procedures', '02HV33Z'),
 (10005817, 28661809, 'procedures', '0B9B8ZX'),
 (10005817, 28661809, 'procedures', '0BH17EZ'),
 (10005817, 28661809, 'procedures', '0W9930Z'),
 (10005817, 28661809, 'procedures', '5A1955Z'),
 (10005817, 28661809, 'diagnoses', 'C7A8'),
 (10005817, 28661809, 'diagnoses', 'C7B8'),
 (10005817, 28661809, 'procedures', 'DW021ZZ'),
 (10005817, 28661809, 'diagnoses', 'E119'),
 (10005817, 28661809, 'diagnoses', 'E883'),
 (10005817, 28661809, 'diagnoses', 'F17210'),
 (10005817, 28661809, 'diagnoses', 'F4310'),
 (10005817, 28661809, 'diagnoses', 'I129'),
 (10005817, 28661809, 'diagnoses', 'I2510'),
 (10005817, 28661809, 'diagnoses', 'I4891'),
 (10005817, 28661809, 'diagnoses', 'I5022'),
 (10005817, 28661809, 'diagnoses', 'I82412'),
 (10005817, 28661809, 'diagnoses', 'I871'),
 (10005817, 28661809, 'diagnoses', 'J189'),
 (10005817, 28661809, 'diagnoses', 'J449'),
 (10005817, 28661809, 'diagnoses', 'J910'),
 (10005817, 28661809, 'diagnoses', 'J9621'),
 (10005817, 28661809, 'diagnoses', 'N170'),
 (10005817, 28661809, 'diagnoses', 'N189'),
 (10005817, 28661809, 'diagnoses', 'R410'),
 (10005817, 28661809, 'diagnoses', 'Z515'),
 (10005817, 28661809, 'diagnoses', 'Z7902'),
 (10005817, 28661809, 'diagnoses', 'Z85048'),
 (10005817, 28661809, 'diagnoses', 'Z951'),
 (10005817, 28661809, 'diagnoses', 'Z955'),
 (10005817, 28661809, 'diagnoses', 'Z9981'),
 (10007818, 22987108, 'procedures', '02H633Z'),
 (10007818, 22987108, 'procedures', '02HV33Z'),
 (10007818, 22987108, 'procedures', '03LP3DZ'),
 (10007818, 22987108, 'procedures', '04LK3DZ'),
 (10007818, 22987108, 'procedures', '0B968ZX'),
 (10007818, 22987108, 'procedures', '0BC78ZZ'),
 (10007818, 22987108, 'procedures', '0BCH8ZZ'),
 (10007818, 22987108, 'procedures', '0BCJ8ZZ'),
 (10007818, 22987108, 'procedures', '0BH17EZ'),
 (10007818, 22987108, 'procedures', '0W9G3ZX'),
 (10007818, 22987108, 'procedures', '0W9G3ZZ'),
 (10007818, 22987108, 'procedures', '3E0436Z'),
 (10007818, 22987108, 'procedures', '3E0G76Z'),
 (10007818, 22987108, 'procedures', '5A1955Z'),
 (10007818, 22987108, 'procedures', '5A1D60Z'),
 (10007818, 22987108, 'diagnoses', 'A4151'),
 (10007818, 22987108, 'procedures', 'B211YZZ'),
 (10007818, 22987108, 'procedures', 'B214YZZ'),
 (10007818, 22987108, 'procedures', 'B518YZA'),
 (10007818, 22987108, 'diagnoses', 'B9561'),
 (10007818, 22987108, 'diagnoses', 'B9689'),
 (10007818, 22987108, 'diagnoses', 'D62'),
 (10007818, 22987108, 'diagnoses', 'D638'),
 (10007818, 22987108, 'diagnoses', 'D684'),
 (10007818, 22987108, 'diagnoses', 'E119'),
 (10007818, 22987108, 'diagnoses', 'E43'),
 (10007818, 22987108, 'diagnoses', 'E871'),
 (10007818, 22987108, 'diagnoses', 'E872'),
 

8. Identify patients diagnosed with `icd_code` starting with "I10" in admission and diagnosed with `icd_code` beginning with "I50" in the same or subsequent admission. List all the distinct `drugs` they were given in the hospital admissions between the first visit having “I10” and last visit having “I50” recorded hospital visits, and ensure there are at least two admissions between the diagnoses of I10 and I50. Exclude the first and last visits
    
    output: subject_id, admission_id, drug
    
    Order By: subject_id(ascending), admission_id(ascending), drug(ascending)

In [50]:
%%sql
WITH I10_Patients AS (
    SELECT DISTINCT d.subject_id, d.hadm_id, a.admittime,
           LEAD(d.hadm_id) OVER (PARTITION BY d.subject_id ORDER BY a.admittime) AS next_hadm_id
    FROM hosp.diagnoses_icd d
    JOIN hosp.admissions a ON d.hadm_id = a.hadm_id
    WHERE d.icd_code LIKE 'I10%'
),
I50_Patients AS (
    SELECT DISTINCT d.subject_id, d.hadm_id, a.admittime
    FROM hosp.diagnoses_icd d
    JOIN hosp.admissions a ON d.hadm_id = a.hadm_id
    WHERE d.icd_code LIKE 'I50%'
),
LinkedAdmissions AS (
    SELECT i10.subject_id, i10.hadm_id AS i10_hadm_id, i10.admittime AS i10_admittime,
           i50.hadm_id AS i50_hadm_id, i50.admittime AS i50_admittime
    FROM I10_Patients i10
    JOIN I50_Patients i50 
    ON i10.subject_id = i50.subject_id
    AND (i10.hadm_id = i50.hadm_id OR i10.next_hadm_id = i50.hadm_id)
),
FirstLastAdmissions AS (
    SELECT subject_id, 
           MIN(hadm_id) FILTER (WHERE icd_code LIKE 'I10%') AS first_hadm_id,  
           MAX(hadm_id) FILTER (WHERE icd_code LIKE 'I50%') AS last_hadm_id    
    FROM hosp.diagnoses_icd
    WHERE subject_id IN (SELECT subject_id FROM LinkedAdmissions)
    GROUP BY subject_id
    HAVING MIN(hadm_id) FILTER (WHERE icd_code LIKE 'I10%') IS NOT NULL
       AND MAX(hadm_id) FILTER (WHERE icd_code LIKE 'I50%') IS NOT NULL
),
IntermediateAdmissions AS (
    SELECT a.subject_id, a.hadm_id
    FROM hosp.admissions a
    JOIN FirstLastAdmissions fa ON a.subject_id = fa.subject_id
    WHERE a.admittime > (SELECT admittime FROM hosp.admissions WHERE hadm_id = fa.first_hadm_id)
      AND a.admittime < (SELECT admittime FROM hosp.admissions WHERE hadm_id = fa.last_hadm_id)
),
ValidPatients AS (
    SELECT ia.subject_id
    FROM IntermediateAdmissions ia
    GROUP BY ia.subject_id
    HAVING COUNT(DISTINCT ia.hadm_id) >= 2
),
DistinctDrugs AS (
    SELECT DISTINCT p.subject_id, p.hadm_id, p.drug
    FROM hosp.prescriptions p
    JOIN IntermediateAdmissions ia ON p.subject_id = ia.subject_id AND p.hadm_id = ia.hadm_id
    JOIN ValidPatients vp ON ia.subject_id = vp.subject_id
)
SELECT subject_id, hadm_id AS admission_id, drug
FROM DistinctDrugs
ORDER BY subject_id ASC, admission_id ASC, drug ASC;

 * postgresql://postgres:***@localhost:5432/db_a1
0 rows affected.


[]

9. Identify patients who were prescribed "amlodipine" or "lisinopril" (`prescriptions.drug`, case-insensitive). For each admission (`hadm_id`) having "amlodipine" or "lisinopril", return the sequence of `services` (string list) received as the patient was transferred, starting from the initial curr_service (where prev_service is NULL) and trace the path till the last recorded service. Use the `prev_service` and `curr_service`. If no service was taken, return an empty list []. For the drug column, return "amlodipine" if only amlodipine was prescribed, "lisinopril" if only lisinopril was prescribed, and "both" if both drugs were given during the visit.
Output Columns: subject_id, hadm_id, drug, [services]
    
    Order By: subject_id (ascending), hadm_id (ascending)

In [ ]:
%%sql
WITH medication_patients AS (
    SELECT subject_id, hadm_id,
           CASE 
               WHEN COUNT(DISTINCT drug) = 2 THEN 'both'
               WHEN MAX(CASE WHEN LOWER(drug) = 'amlodipine' THEN 1 ELSE 0 END) = 1 THEN 'amlodipine'
               WHEN MAX(CASE WHEN LOWER(drug) = 'lisinopril' THEN 1 ELSE 0 END) = 1 THEN 'lisinopril'
           END AS drug
    FROM hosp.prescriptions
    WHERE LOWER(drug) IN ('amlodipine', 'lisinopril')
    GROUP BY subject_id, hadm_id
),
service_sequence AS (
    SELECT s.subject_id, s.hadm_id,
           ARRAY_TO_STRING(ARRAY_AGG(curr_service ORDER BY transfertime), ', ') AS services
    FROM hosp.services s
    GROUP BY s.subject_id, s.hadm_id
)
SELECT mp.subject_id, mp.hadm_id, mp.drug, COALESCE(ss.services, '') AS "[services]"
FROM medication_patients mp
LEFT JOIN service_sequence ss ON mp.subject_id = ss.subject_id AND mp.hadm_id = ss.hadm_id
ORDER BY mp.subject_id, mp.hadm_id;


 * postgresql://postgres:***@localhost:5432/db_a1
59 rows affected.


[(10002428, 23473524, 'lisinopril', 'MED'),
 (10002428, 25797028, 'lisinopril', 'MED'),
 (10002428, 28676446, 'lisinopril', 'ORTHO'),
 (10003400, 26090619, 'both', 'MED'),
 (10004235, 24181354, 'lisinopril', 'MED'),
 (10004422, 21255400, 'lisinopril', 'CMED, CSURG'),
 (10004457, 28723315, 'lisinopril', 'CMED'),
 (10004733, 27411876, 'both', 'MED, NMED'),
 (10005817, 20626031, 'lisinopril', 'SURG'),
 (10012552, 27089790, 'lisinopril', 'CSURG'),
 (10012853, 20457729, 'both', 'SURG'),
 (10012853, 22539296, 'both', 'MED'),
 (10012853, 26369609, 'lisinopril', 'CMED'),
 (10012853, 26739864, 'both', 'SURG'),
 (10012853, 27882036, 'both', 'MED'),
 (10014354, 27487226, 'lisinopril', 'MED, OMED, MED'),
 (10015860, 20790339, 'amlodipine', 'MED'),
 (10015860, 20854119, 'both', 'MED'),
 (10015860, 22413744, 'amlodipine', 'MED'),
 (10015860, 22607171, 'both', 'MED'),
 (10015860, 24698912, 'both', 'MED'),
 (10015860, 25085565, 'lisinopril', 'CMED, MED, SURG'),
 (10015860, 25103777, 'lisinopril', 'MED'),
 (10015860, 26352758, 'lisinopril', 'ORTHO'),
 (10015860, 27670224, 'lisinopril', 'MED'),
 (10015860, 28196804, 'lisinopril', 'MED'),
 (10015860, 28236161, 'lisinopril', 'SURG'),
 (10015860, 28613200, 'lisinopril', 'SURG'),
 (10015931, 24420677, 'lisinopril', 'CMED, MED, CMED'),
 (10017492, 27672872, 'amlodipine', 'NMED'),
 (10018081, 25973915, 'lisinopril', 'SURG'),
 (10018328, 23786647, 'amlodipine', 'NSURG'),
 (10018328, 26706939, 'amlodipine', 'SURG, MED'),
 (10018501, 28479513, 'amlodipine', 'NSURG'),
 (10019003, 28003918, 'lisinopril', 'GYN'),
 (10019172, 24997044, 'both', 'CSURG'),
 (10020306, 23052851, 'lisinopril', 'MED'),
 (10021118, 24490144, 'lisinopril', 'CMED, CSURG'),
 (10022017, 22342963, 'lisinopril', 'CSURG'),
 (10022281, 29642388, 'amlodipine', 'VSURG'),
 (10023117, 28872262, 'lisinopril', 'CMED, CSURG, CMED'),
 (10023117, 29839885, 'lisinopril', 'CMED'),
 (10023771, 20044587, 'amlodipine', 'CSURG'),
 (10025463, 24470193, 'lisinopril', 'NSURG'),
 (10025463, 27327816, 'lisinopril', 'CMED'),
 (10031404, 21606243, 'amlodipine', 'CMED'),
 (10032725, 25177949, 'lisinopril', 'MED, OMED'),
 (10035631, 20385771, 'amlodipine', 'OMED'),
 (10037928, 20192635, 'amlodipine', 'MED'),
 (10037928, 22326517, 'amlodipine', 'MED'),
 (10037928, 22490490, 'amlodipine', 'MED'),
 (10037928, 23721604, 'amlodipine', 'MED'),
 (10037928, 24225421, 'amlodipine', 'MED'),
 (10037928, 24656677, 'amlodipine', 'MED'),
 (10037928, 24885579, 'amlodipine', 'SURG'),
 (10037928, 29802992, 'amlodipine', 'MED'),
 (10038933, 25129047, 'amlodipine', 'NSURG'),
 (10039997, 22484749, 'both', 'NMED'),
 (10039997, 24294180, 'both', 'NSURG')]

10. Give the patients diagnosed with `diagnoses.icd_code` starting with "I2" during their first admission, and who were readmitted within 6 months( 180 days) after discharge. Retrieve the time gap between the first admission discharge and second admission admit time (in the same format as admittime). Find the list of services (cur_service) (in sequence) the patients used for the second admission. Return string list for the same. 
    
    Output Columns: subject_id, second_hadm_id, time_gap_between_admissions, [services]
    
    Order By: len([services]) (Decreasing), time_gap_between_admissions(decreasing), subject_id (Ascending), hadm_id(ascending).

In [47]:
%%sql
select * from hosp.admissions limit 5;


 * postgresql://postgres:***@localhost:5432/db_a1
5 rows affected.


[(10004235, 24181354, '2196-02-24 14:38:00', '2196-03-04 14:02:00', None, 'URGENT', 'P03YMR', 'TRANSFER FROM HOSPITAL', 'SKILLED NURSING FACILITY', 'Medicaid', 'ENGLISH', 'SINGLE', 'BLACK/CAPE VERDEAN', '2196-02-24 12:15:00', '2196-02-24 17:07:00', 0),
 (10009628, 25926192, '2153-09-17 17:08:00', '2153-09-25 13:20:00', None, 'URGENT', 'P41R5N', 'TRANSFER FROM HOSPITAL', 'HOME HEALTH CARE', 'Medicaid', '?', 'MARRIED', 'HISPANIC/LATINO - PUERTO RICAN', None, None, 0),
 (10018081, 23983182, '2134-08-18 02:02:00', '2134-08-23 19:35:00', None, 'URGENT', 'P233F6', 'TRANSFER FROM HOSPITAL', 'SKILLED NURSING FACILITY', 'Medicare', 'ENGLISH', 'MARRIED', 'WHITE', '2134-08-17 16:24:00', '2134-08-18 03:15:00', 0),
 (10006053, 22942076, '2111-11-13 23:39:00', '2111-11-15 17:20:00', '2111-11-15 17:20:00', 'URGENT', 'P38TI6', 'TRANSFER FROM HOSPITAL', 'DIED', 'Medicaid', 'ENGLISH', None, 'UNKNOWN', None, None, 1),
 (10031404, 21606243, '2113-08-04 18:46:00', '2113-08-06 20:57:00', None, 'URGENT', 'P07HDB', 'TRANSFER FROM HOSPITAL', 'HOME', 'Other', 'ENGLISH', 'WIDOWED', 'WHITE', None, None, 0)]

In [48]:
%%sql
WITH FirstAdmission AS (
    SELECT d.subject_id, a.hadm_id AS first_hadm_id, 
           TO_TIMESTAMP(a.dischtime, 'YYYY-MM-DD HH24:MI:SS') AS dischtime
    FROM hosp.diagnoses_icd d
    JOIN hosp.admissions a ON d.hadm_id = a.hadm_id
    WHERE d.icd_code LIKE 'I2%'
    AND a.admittime = (SELECT MIN(admittime) FROM hosp.admissions WHERE subject_id = a.subject_id)
),
SecondAdmission AS (
    SELECT fa.subject_id, a.hadm_id AS second_hadm_id, 
           TO_TIMESTAMP(a.admittime, 'YYYY-MM-DD HH24:MI:SS') AS admittime,
           fa.dischtime,
           age(TO_TIMESTAMP(a.admittime, 'YYYY-MM-DD HH24:MI:SS'), fa.dischtime) AS time_gap
    FROM FirstAdmission fa
    JOIN hosp.admissions a ON fa.subject_id = a.subject_id
    WHERE TO_TIMESTAMP(a.admittime, 'YYYY-MM-DD HH24:MI:SS') > fa.dischtime 
      AND TO_TIMESTAMP(a.admittime, 'YYYY-MM-DD HH24:MI:SS') <= fa.dischtime + INTERVAL '180 days'
    ORDER BY fa.subject_id, a.admittime
),
ServicesList AS (
    SELECT sa.subject_id, sa.second_hadm_id, 
           STRING_AGG(s.curr_service, ',' ORDER BY s.transfertime) AS services
    FROM SecondAdmission sa
    LEFT JOIN hosp.services s ON sa.second_hadm_id = s.hadm_id
    GROUP BY sa.subject_id, sa.second_hadm_id, sa.time_gap, sa.dischtime
)
SELECT sa.subject_id, sa.second_hadm_id, 
       TO_CHAR(sa.time_gap, 'YYYY-MM-DD HH24:MI:SS') AS time_gap_between_admissions, 
       COALESCE(sl.services, '[]') AS "[services]"
FROM SecondAdmission sa
LEFT JOIN ServicesList sl ON sa.subject_id = sl.subject_id AND sa.second_hadm_id = sl.second_hadm_id
WHERE sa.second_hadm_id IN (24420677, 20611796, 28506150)
ORDER BY LENGTH(services) DESC, sa.time_gap DESC, sa.subject_id ASC, sa.second_hadm_id ASC;




 * postgresql://postgres:***@localhost:5432/db_a1
3 rows affected.


[(10015931, 24420677, '0000-00-19 10:01:00', 'CMED,MED,CMED'),
 (10019385, 20611796, '0000-00-07 11:31:00', 'CMED,CSURG'),
 (10016742, 28506150, '0000-00-04 09:20:00', 'MED')]

## Graph Queries

In [242]:
%%sql
WITH earliest_admissions AS (
    SELECT subject_id, hadm_id, admittime, dischtime
    FROM hosp.admissions
    ORDER BY TO_TIMESTAMP(admittime, 'YYYY-MM-DD HH24:MI:SS')
    LIMIT 200
),
overlapping_admissions AS (
    SELECT a1.subject_id AS subject_id1, 
           a2.subject_id AS subject_id2,
           a1.hadm_id AS hadm1,
           a2.hadm_id AS hadm2
    FROM earliest_admissions a1
    JOIN earliest_admissions a2 
    ON a1.subject_id < a2.subject_id -- Ensure unique edges (undirected graph)
    AND TO_TIMESTAMP(a1.admittime, 'YYYY-MM-DD HH24:MI:SS') < TO_TIMESTAMP(a2.dischtime, 'YYYY-MM-DD HH24:MI:SS')
    AND TO_TIMESTAMP(a2.admittime, 'YYYY-MM-DD HH24:MI:SS') < TO_TIMESTAMP(a1.dischtime, 'YYYY-MM-DD HH24:MI:SS')
),
shared_diagnoses AS (
    SELECT DISTINCT d1.subject_id AS subject_id1, 
                    d2.subject_id AS subject_id2,
                    d1.hadm_id AS hadm1,
                    d2.hadm_id AS hadm2
    FROM hosp.diagnoses_icd d1
    JOIN hosp.diagnoses_icd d2 
    ON d1.subject_id < d2.subject_id  
    AND d1.icd_code = d2.icd_code
    AND d1.icd_version = d2.icd_version
    AND d1.hadm_id IN (
        SELECT hadm1 FROM overlapping_admissions oa
        WHERE oa.subject_id1 = d1.subject_id AND oa.subject_id2 = d2.subject_id
    )
    AND d2.hadm_id IN (
        SELECT hadm2 FROM overlapping_admissions oa
        WHERE oa.subject_id1 = d1.subject_id AND oa.subject_id2 = d2.subject_id
    )
)
SELECT DISTINCT o.subject_id1, o.subject_id2
FROM overlapping_admissions o
JOIN shared_diagnoses s ON o.subject_id1 = s.subject_id1 AND o.subject_id2 = s.subject_id2
ORDER BY o.subject_id1, o.subject_id2;

 * postgresql://postgres:***@localhost:5432/db_a1
4 rows affected.


[(10005817, 10020306),
 (10010867, 10040025),
 (10018081, 10039997),
 (10037861, 10038081)]

In [243]:
%%sql
WITH earliest_admissions AS (
    -- Select the earliest 200 admissions based on admission time
    SELECT subject_id, hadm_id, admittime, dischtime
    FROM hosp.admissions
    ORDER BY TO_TIMESTAMP(admittime, 'YYYY-MM-DD HH24:MI:SS')
    LIMIT 200
),
directed_edges AS (
    -- Find directed edges based on overlapping admission periods
    SELECT DISTINCT a1.subject_id AS subject_id1, 
                    a2.subject_id AS subject_id2
    FROM earliest_admissions a1
    JOIN earliest_admissions a2 
    ON a1.subject_id <> a2.subject_id  -- Allow directionality (a → b and b → a are separate)
    WHERE 
    TO_TIMESTAMP(a1.admittime, 'YYYY-MM-DD HH24:MI:SS') 
        < TO_TIMESTAMP(a2.dischtime, 'YYYY-MM-DD HH24:MI:SS')
    AND 
    TO_TIMESTAMP(a1.dischtime, 'YYYY-MM-DD HH24:MI:SS') 
        > TO_TIMESTAMP(a2.admittime, 'YYYY-MM-DD HH24:MI:SS')
)
SELECT subject_id1, subject_id2
FROM directed_edges
ORDER BY subject_id1, subject_id2;


 * postgresql://postgres:***@localhost:5432/db_a1
34 rows affected.


[(10002428, 10019003),
 (10003400, 10006580),
 (10003400, 10039997),
 (10004457, 10032725),
 (10004457, 10038933),
 (10004733, 10023117),
 (10005817, 10020306),
 (10005866, 10010867),
 (10005866, 10014354),
 (10006580, 10003400),
 (10010867, 10005866),
 (10010867, 10040025),
 (10014354, 10005866),
 (10014354, 10020740),
 (10016150, 10039708),
 (10018081, 10039997),
 (10019003, 10002428),
 (10020306, 10005817),
 (10020740, 10014354),
 (10021487, 10024043),
 (10021487, 10037861),
 (10023117, 10004733),
 (10023771, 10035631),
 (10024043, 10021487),
 (10032725, 10004457),
 (10035631, 10023771),
 (10037861, 10021487),
 (10037861, 10038081),
 (10038081, 10037861),
 (10038933, 10004457),
 (10039708, 10016150),
 (10039997, 10003400),
 (10039997, 10018081),
 (10040025, 10010867)]

**Graph-1 :** Apply the concept of graphical analysis to the given dataset to construct an undirected, unweighted graph based on overlapping hospital admission periods.

- Consider the earliest 200 admissions in the dataset, where subject_id will represent a node in the graph.
- There exists an undirected edge between two patients if they were admitted to the hospital at least once during an overlapping period and they  share atleast one ICD  diagnosis during overlapping hospital stays(use icd_code and icd_version).

**Graph-2**: Apply the concept of graphical analysis to the given dataset to construct a directed, unweighted graph based on overlapping hospital admission periods.

- Consider the earliest 200 admissions in the dataset, where subject_id will represent a node in the graph.
- There exists an edge between two patients if they were admitted to the hospital at least once during an overlapping period  . In this graph the  edge (a,b)  and edge (b,a) can be considered two separate edges.

1. Considering **Graph-1** ,create a table edge_list that lists all edges in the graph. Ensure there are no duplicate edges; i.e., if an edge (a,b) exists, (b,a) should not appear in the list, and there are no self-edges; a patient cannot have an edge to themselves.

       Output: subject_id1 , subject_id2 

       (note: subject_id1< subject_id2)

       Order by: subject_id1 (ascending) ,subject_id2(ascending)

In [20]:
%%sql
DROP TABLE IF EXISTS edge_list;

 * postgresql://postgres:***@localhost:5432/db_a1
Done.


[]

In [255]:
%%sql
WITH earliest_admissions AS (
    SELECT subject_id, hadm_id, admittime, dischtime
    FROM hosp.admissions
    ORDER BY TO_TIMESTAMP(admittime, 'YYYY-MM-DD HH24:MI:SS')
    LIMIT 200
),
overlapping_admissions AS (
    SELECT a1.subject_id AS subject_id1, 
           a2.subject_id AS subject_id2,
           a1.hadm_id AS hadm1,
           a2.hadm_id AS hadm2
    FROM earliest_admissions a1
    JOIN earliest_admissions a2 
    ON a1.subject_id < a2.subject_id -- Ensure unique edges (undirected graph)
    AND TO_TIMESTAMP(a1.admittime, 'YYYY-MM-DD HH24:MI:SS') < TO_TIMESTAMP(a2.dischtime, 'YYYY-MM-DD HH24:MI:SS')
    AND TO_TIMESTAMP(a2.admittime, 'YYYY-MM-DD HH24:MI:SS') < TO_TIMESTAMP(a1.dischtime, 'YYYY-MM-DD HH24:MI:SS')
),
shared_diagnoses AS (
    SELECT DISTINCT d1.subject_id AS subject_id1, 
                    d2.subject_id AS subject_id2,
                    d1.hadm_id AS hadm1,
                    d2.hadm_id AS hadm2
    FROM hosp.diagnoses_icd d1
    JOIN hosp.diagnoses_icd d2 
    ON d1.subject_id < d2.subject_id  
    AND d1.icd_code = d2.icd_code
    AND d1.icd_version = d2.icd_version
    AND d1.hadm_id IN (
        SELECT hadm1 FROM overlapping_admissions oa
        WHERE oa.subject_id1 = d1.subject_id AND oa.subject_id2 = d2.subject_id
    )
    AND d2.hadm_id IN (
        SELECT hadm2 FROM overlapping_admissions oa
        WHERE oa.subject_id1 = d1.subject_id AND oa.subject_id2 = d2.subject_id
    )
)
SELECT DISTINCT o.subject_id1, o.subject_id2
FROM overlapping_admissions o
JOIN shared_diagnoses s ON o.subject_id1 = s.subject_id1 AND o.subject_id2 = s.subject_id2
ORDER BY o.subject_id1, o.subject_id2;




 * postgresql://postgres:***@localhost:5432/db_a1
4 rows affected.


[(10005817, 10020306),
 (10010867, 10040025),
 (10018081, 10039997),
 (10037861, 10038081)]

In [21]:
%%sql
create or replace view ordered_nodes as(
 select  subject_id, hadm_id, admittime, dischtime 
    from hosp.admissions 
    order by admittime 
    limit 200
    
);
create or replace view nodes as( 
    select distinct ordered_nodes.subject_id, ordered_nodes.hadm_id, diagnoses_icd.icd_code, diagnoses_icd.icd_version, ordered_nodes.admittime, ordered_nodes.dischtime
    from hosp.diagnoses_icd
	join ordered_nodes  on diagnoses_icd.hadm_id = ordered_nodes.hadm_id and diagnoses_icd.subject_id = ordered_nodes.subject_id
    where ordered_nodes.dischtime is not null and ordered_nodes.admittime is not null and ordered_nodes.admittime<=ordered_nodes.dischtime
); --
 create or replace view edge_list(subject_id1, subject_id2) as( 
    select distinct n1.subject_id , n2.subject_id  from nodes n1 join nodes n2 
    on n1.subject_id != n2.subject_id 
    where ((n1.admittime <= n2.admittime and n2.admittime <= n1.dischtime )
    or (n2.admittime <= n1.admittime and n1.admittime <= n2.dischtime) )    
    and n1.icd_code = n2.icd_code and n1.icd_version = n2.icd_version
	AND n1.subject_id < n2.subject_id
	order by n1.subject_id asc,n2.subject_id
);


select * from edge_list

 * postgresql://postgres:***@localhost:5432/db_a1
Done.
Done.
Done.
4 rows affected.


[(10005817, 10020306),
 (10010867, 10040025),
 (10018081, 10039997),
 (10037861, 10038081)]

2. Considering **Graph-2** , write a  query that checks if there is an edge between the node subject_id = 10006580 and  subject_id=10003400 , if present should return 1 or else 0   

        output :path_exists

In [235]:
%%sql
WITH earliest_admissions AS (
    SELECT subject_id, hadm_id, admittime, dischtime
    FROM hosp.admissions
    ORDER BY TO_TIMESTAMP(admittime, 'YYYY-MM-DD HH24:MI:SS')
    LIMIT 200
),
directed_edges AS (
    SELECT DISTINCT a1.subject_id AS subject_id1, 
                    a2.subject_id AS subject_id2
    FROM earliest_admissions a1
    JOIN earliest_admissions a2 
    ON a1.subject_id <> a2.subject_id
    WHERE 
    TO_TIMESTAMP(a1.admittime, 'YYYY-MM-DD HH24:MI:SS') 
        < TO_TIMESTAMP(a2.dischtime, 'YYYY-MM-DD HH24:MI:SS')
    AND 
    TO_TIMESTAMP(a1.dischtime, 'YYYY-MM-DD HH24:MI:SS') 
        > TO_TIMESTAMP(a2.admittime, 'YYYY-MM-DD HH24:MI:SS')
),
directed_edge_list AS (
    SELECT subject_id1, subject_id2
    FROM directed_edges
    ORDER BY subject_id1, subject_id2
)

SELECT CASE 
           WHEN EXISTS (
               SELECT 1 
               FROM directed_edge_list 
               WHERE (subject_id1 = 10006580 AND subject_id2 = 10003400) 
                  OR (subject_id1 = 10003400 AND subject_id2 = 10006580)
           ) 
           THEN 1 ELSE 0 
       END AS path_exists;



 * postgresql://postgres:***@localhost:5432/db_a1
1 rows affected.


[(1,)]

In [22]:
%%sql
create or replace view temp2 as(
 select  subject_id, hadm_id, admittime, dischtime 
    from hosp.admissions 
    order by admittime 
    limit 200
);

create or replace view edge_list1(subject_id1,subject_id2) as( 
    select distinct n1.subject_id  , n2.subject_id   
	from temp2 n1 join temp2 n2 
    on n1.subject_id != n2.subject_id 
    where ((n1.admittime <= n2.admittime and n2.admittime <= n1.dischtime )
    or (n2.admittime <= n1.admittime and n1.admittime <= n2.dischtime) )    
   
	 -- Add condition to enforce that subject_id1 < subject_id2
   
	order by n1.subject_id asc
);

WITH RECURSIVE shortest_paths AS (
    -- Base case: Start from the given subject_id
    SELECT 
        subject_id1 AS start_id, 
        subject_id2 AS connected_id, 
        1 AS path_length,
        --ARRAY[subject_id1 || '-' || subject_id2] AS visited_edges -- Track visited edges
		 ARRAY[subject_id1 || '-' || subject_id2] AS visited_edges
    FROM edge_list1
    WHERE subject_id1 = 10006580

    UNION ALL

    -- Recursive case: Find all connected nodes, ensuring edges are not revisited
    SELECT 
        sp.start_id, 
        e.subject_id2 AS connected_id, 
        sp.path_length + 1,
        sp.visited_edges || (sp.connected_id || '-' || e.subject_id2) -- Append the current edge to the visited list
    FROM shortest_paths sp
    JOIN edge_list1 e 
        ON sp.connected_id = e.subject_id1
		
   WHERE (NOT (sp.connected_id || '-' || e.subject_id2) = ANY (sp.visited_edges))  and sp.start_id <> e.subject_id2 -- Skip revisited edges
)
SELECT 
    CASE 
        WHEN EXISTS (
            SELECT 1 
            FROM shortest_paths 
            WHERE connected_id = 10003400 -- Replace 'x' with the desired subject_id
        ) THEN 1
        ELSE 0
    END AS path_exists;

 * postgresql://postgres:***@localhost:5432/db_a1
Done.
Done.
1 rows affected.


[(1,)]

3. Considering **Graph-2** ,find the shortest path between subject_id=10038081 and subject_id=10021487

         output:path_length

In [238]:
%%sql
WITH RECURSIVE earliest_admissions AS (
    SELECT subject_id, hadm_id, admittime, dischtime
    FROM hosp.admissions
    ORDER BY TO_TIMESTAMP(admittime, 'YYYY-MM-DD HH24:MI:SS')
    LIMIT 200
),
directed_edges AS (
    SELECT DISTINCT a1.subject_id AS subject_id1, 
                    a2.subject_id AS subject_id2
    FROM earliest_admissions a1
    JOIN earliest_admissions a2 
    ON a1.subject_id <> a2.subject_id
    WHERE 
    TO_TIMESTAMP(a1.admittime, 'YYYY-MM-DD HH24:MI:SS') 
        < TO_TIMESTAMP(a2.dischtime, 'YYYY-MM-DD HH24:MI:SS')
    AND 
    TO_TIMESTAMP(a1.dischtime, 'YYYY-MM-DD HH24:MI:SS') 
        > TO_TIMESTAMP(a2.admittime, 'YYYY-MM-DD HH24:MI:SS')
),
directed_edge_list AS (
    SELECT subject_id1, subject_id2
    FROM directed_edges
    ORDER BY subject_id1, subject_id2
),
shortest_path AS (
    
    SELECT subject_id1 AS start_id, subject_id2 AS end_id, 1 AS path_length
    FROM directed_edge_list
    WHERE subject_id1 = 10038081
    
    UNION ALL

    
    SELECT sp.start_id, de.subject_id2, sp.path_length + 1
    FROM shortest_path sp
    JOIN directed_edge_list de ON sp.end_id = de.subject_id1
    WHERE sp.path_length < 20
)
SELECT MIN(path_length) AS path_length
FROM shortest_path
WHERE end_id = 10021487;


 * postgresql://postgres:***@localhost:5432/db_a1
1 rows affected.


[(2,)]

In [23]:
%%sql
create or replace view temp2 as(
 select  subject_id, hadm_id, admittime, dischtime 
    from hosp.admissions 
    order by admittime 
    limit 200
);

create or replace view edge_list1(subject_id1,subject_id2) as( 
    select distinct n1.subject_id  , n2.subject_id   
	from temp2 n1 join temp2 n2 
    on n1.subject_id != n2.subject_id 
    where ((n1.admittime <= n2.admittime and n2.admittime <= n1.dischtime )
    or (n2.admittime <= n1.admittime and n1.admittime <= n2.dischtime) )    
   
	 -- Add condition to enforce that subject_id1 < subject_id2
   
	order by n1.subject_id asc
);
WITH RECURSIVE shortest_paths AS (
    -- Base case: Start from the given subject_id
    SELECT 
        subject_id1 AS start_id, 
        subject_id2 AS connected_id, 
        1 AS path_length,
        --ARRAY[subject_id1 || '-' || subject_id2] AS visited_edges -- Track visited edges
		 ARRAY[subject_id1 || '-' || subject_id2] AS visited_edges
    FROM edge_list1
    WHERE subject_id1 = 10038081

    UNION ALL

    -- Recursive case: Find all connected nodes, ensuring edges are not revisited
    SELECT 
        sp.start_id, 
        e.subject_id2 AS connected_id, 
        sp.path_length + 1,
        sp.visited_edges || (sp.connected_id || '-' || e.subject_id2) -- Append the current edge to the visited list
    FROM shortest_paths sp
    JOIN edge_list1 e 
        ON sp.connected_id = e.subject_id1
		
   WHERE (NOT (sp.connected_id || '-' || e.subject_id2) = ANY (sp.visited_edges))  and sp.start_id <> e.subject_id2 -- Skip revisited edges
)
select (SELECT  path_length
FROM (
    SELECT 
        start_id, 
        connected_id, 
        path_length, 
        ROW_NUMBER() OVER (PARTITION BY start_id, connected_id ORDER BY path_length ASC) AS rn
    FROM shortest_paths
	WHERE connected_id = 10021487
) ranked_paths
WHERE rn = 1
order by path_length asc , connected_id asc

)

 * postgresql://postgres:***@localhost:5432/db_a1
Done.
Done.
1 rows affected.


[(2,)]

4. Considering **Graph-2** ,write a query to check how many nodes ,direct or indirect ,are connected to subject_id =10038081

        output : count 

In [239]:
%%sql
WITH RECURSIVE earliest_admissions AS (
    SELECT subject_id, hadm_id, admittime, dischtime
    FROM hosp.admissions
    ORDER BY TO_TIMESTAMP(admittime, 'YYYY-MM-DD HH24:MI:SS')
    LIMIT 200
),
directed_edges AS (
    SELECT DISTINCT a1.subject_id AS subject_id1, 
                    a2.subject_id AS subject_id2
    FROM earliest_admissions a1
    JOIN earliest_admissions a2 
    ON a1.subject_id <> a2.subject_id
    WHERE 
    TO_TIMESTAMP(a1.admittime, 'YYYY-MM-DD HH24:MI:SS') 
        < TO_TIMESTAMP(a2.dischtime, 'YYYY-MM-DD HH24:MI:SS')
    AND 
    TO_TIMESTAMP(a1.dischtime, 'YYYY-MM-DD HH24:MI:SS') 
        > TO_TIMESTAMP(a2.admittime, 'YYYY-MM-DD HH24:MI:SS')
),
directed_edge_list AS (
    SELECT subject_id1, subject_id2
    FROM directed_edges
    ORDER BY subject_id1, subject_id2
),
reachable_nodes AS (
    SELECT subject_id2 AS connected_id 
    FROM directed_edge_list 
    WHERE subject_id1 = 10038081
    
    UNION

    SELECT de.subject_id2 
    FROM reachable_nodes rn
    JOIN directed_edge_list de ON rn.connected_id = de.subject_id1
)
SELECT COUNT(DISTINCT connected_id) AS count FROM reachable_nodes;


 * postgresql://postgres:***@localhost:5432/db_a1
1 rows affected.


[(4,)]

In [24]:
%%sql
create or replace view temp2 as(
 select  subject_id, hadm_id, admittime, dischtime 
    from hosp.admissions 
    order by admittime 
    limit 200
);

create or replace view edge_list1(subject_id1,subject_id2) as( 
    select distinct n1.subject_id  , n2.subject_id   
	from temp2 n1 join temp2 n2 
    on n1.subject_id != n2.subject_id 
    where ((n1.admittime <= n2.admittime and n2.admittime <= n1.dischtime )
    or (n2.admittime <= n1.admittime and n1.admittime <= n2.dischtime) )    
   
	 -- Add condition to enforce that subject_id1 < subject_id2
   
	order by n1.subject_id asc
);
WITH RECURSIVE shortest_paths AS (
    -- Base case: Start from the given subject_id
    SELECT 
        subject_id1 AS start_id, 
        subject_id2 AS connected_id, 
        1 AS path_length,
        --ARRAY[subject_id1 || '-' || subject_id2] AS visited_edges -- Track visited edges
		 ARRAY[subject_id1 || '-' || subject_id2] AS visited_edges
    FROM edge_list1
    WHERE subject_id1 = 10038081

    UNION ALL

    -- Recursive case: Find all connected nodes, ensuring edges are not revisited
    SELECT 
        sp.start_id, 
        e.subject_id2 AS connected_id, 
        sp.path_length + 1,
        sp.visited_edges || (sp.connected_id || '-' || e.subject_id2) -- Append the current edge to the visited list
    FROM shortest_paths sp
    JOIN edge_list1 e 
        ON sp.connected_id = e.subject_id1
		
   WHERE (NOT (sp.connected_id || '-' || e.subject_id2) = ANY (sp.visited_edges))  and sp.start_id <> e.subject_id2 -- Skip revisited edges
)

SELECT count(1) from (
select distinct start_id ,connected_id
from shortest_paths
) as count

 * postgresql://postgres:***@localhost:5432/db_a1
Done.
Done.
1 rows affected.


[(3,)]

5. Consider **Graph-2** ,write a  query to calculate the shortest paths between a given subject_id=10037861 and all other direct or indirect , connected subject_id s , and retrieve distinct pairs of start_id and connected_id with the minimum  path length.

        output columns : start_id ,connected_id ,path_length (where start_id =10037861  for every 

        output row)

       order by path_length (asc) ,connected_id( asc)

        (Note that for any node x if x is not connected to  10037861 , there should be no entry for that       

        pair i.e output  10037861,x,null  is not allowed).

In [244]:
%%sql
WITH RECURSIVE earliest_admissions AS (
    SELECT subject_id, hadm_id, admittime, dischtime
    FROM hosp.admissions
    ORDER BY TO_TIMESTAMP(admittime, 'YYYY-MM-DD HH24:MI:SS')
    LIMIT 200
),
directed_edges AS (
    SELECT DISTINCT a1.subject_id AS subject_id1, 
                    a2.subject_id AS subject_id2
    FROM earliest_admissions a1
    JOIN earliest_admissions a2 
    ON a1.subject_id <> a2.subject_id
    WHERE 
    TO_TIMESTAMP(a1.admittime, 'YYYY-MM-DD HH24:MI:SS') 
        < TO_TIMESTAMP(a2.dischtime, 'YYYY-MM-DD HH24:MI:SS')
    AND 
    TO_TIMESTAMP(a1.dischtime, 'YYYY-MM-DD HH24:MI:SS') 
        > TO_TIMESTAMP(a2.admittime, 'YYYY-MM-DD HH24:MI:SS')
),
directed_edge_list AS (
    SELECT subject_id1, subject_id2
    FROM directed_edges
    ORDER BY subject_id1, subject_id2
),
all_paths AS (
    SELECT subject_id1 AS start_id, subject_id2 AS connected_id, 1 AS path_length
    FROM directed_edge_list
    WHERE subject_id1 = 10037861
    
    UNION ALL

    SELECT ap.start_id, de.subject_id2, ap.path_length + 1
    FROM all_paths ap
    JOIN directed_edge_list de ON ap.connected_id = de.subject_id1
    WHERE ap.path_length < 20
)
SELECT DISTINCT start_id, connected_id, MIN(path_length) AS path_length
FROM all_paths
WHERE start_id <> connected_id
GROUP BY start_id, connected_id
ORDER BY path_length ASC, connected_id ASC;


 * postgresql://postgres:***@localhost:5432/db_a1
3 rows affected.


[(10037861, 10021487, 1), (10037861, 10038081, 1), (10037861, 10024043, 2)]

In [25]:
%%sql
create or replace view temp2 as(
 select  subject_id, hadm_id, admittime, dischtime 
    from hosp.admissions 
    order by admittime 
    limit 200
);

create or replace view edge_list1(subject_id1,subject_id2) as( 
    select distinct n1.subject_id  , n2.subject_id   
	from temp2 n1 join temp2 n2 
    on n1.subject_id != n2.subject_id 
    where ((n1.admittime <= n2.admittime and n2.admittime <= n1.dischtime )
    or (n2.admittime <= n1.admittime and n1.admittime <= n2.dischtime) )    
   
	 -- Add condition to enforce that subject_id1 < subject_id2
   
	order by n1.subject_id asc
);


WITH RECURSIVE shortest_paths AS (
    -- Base case: Start from the given subject_id
    SELECT 
        subject_id1 AS start_id, 
        subject_id2 AS connected_id, 
        1 AS path_length,
        --ARRAY[subject_id1 || '-' || subject_id2] AS visited_edges -- Track visited edges
		 ARRAY[subject_id1 || '-' || subject_id2] AS visited_edges
    FROM edge_list1
    WHERE subject_id1 = 10037861

    UNION ALL

    -- Recursive case: Find all connected nodes, ensuring edges are not revisited
    SELECT 
        sp.start_id, 
        e.subject_id2 AS connected_id, 
        sp.path_length + 1,
        sp.visited_edges || (sp.connected_id || '-' || e.subject_id2) -- Append the current edge to the visited list
    FROM shortest_paths sp
    JOIN edge_list1 e 
        ON sp.connected_id = e.subject_id1
		
   WHERE (NOT (sp.connected_id || '-' || e.subject_id2) = ANY (sp.visited_edges))  and sp.start_id <> e.subject_id2 -- Skip revisited edges
)
SELECT start_id, connected_id, path_length
FROM (
    SELECT 
        start_id, 
        connected_id, 
        path_length, 
        ROW_NUMBER() OVER (PARTITION BY start_id, connected_id ORDER BY path_length ASC) AS rn
    FROM shortest_paths
) ranked_paths
WHERE rn = 1
order by path_length asc , connected_id asc;

 * postgresql://postgres:***@localhost:5432/db_a1
Done.
Done.
3 rows affected.


[(10037861, 10021487, 1), (10037861, 10038081, 1), (10037861, 10024043, 2)]